./box_month_3_.exe
./d2j_3_.exe
./d2o_3_.exe
./d2u_3_.exe
./d2w_3_.exe
./date_to_julian_3_.exe
./date_to_unix_3_.exe
./days2sec_3_.exe
./dow_3_.exe
./easter_3_.exe
./fmtdate_3_.exe
./fmtdate_usage_3_.exe
./guessdate_3_.exe
./j2d_3_.exe
./julian_to_date_3_.exe
./mo2d_3_.exe
./mo2v_3_.exe
./moon_fullness_3_.exe
./now_3_.exe
./o2d_3_.exe
./ordinal_seconds_3_.exe
./ordinal_to_date_3_.exe
./phase_of_moon_3_.exe
./sec2days_3_.exe
./u2d_3_.exe
./unix_to_date_3_.exe
./v2mo_3_.exe
./w2d_3_.exe
