M_time: m_time_duplicate Module Reference
m_time_duplicate Module Reference
Data Types
interface string_to_value
interface v2s
Functions/Subroutines
subroutine, public substitute (targetline, old, new, ierr, start, end)
NAME
substitute(3f) - [M_strings:EDITING] subroutine globally substitutes one substring for another in string (LICENSE:PD)
elemental pure character(len(str)) function, public upper (str, begin, end)
NAME
upper(3f) - [M_strings:CASE] changes a string to uppercase (LICENSE:PD)
elemental pure character(len(str)) function, public lower (str, begin, end)
NAME
lower(3f) - [M_strings:CASE] changes a string to lowercase over specified range (LICENSE:PD)
subroutine stderr (string)
pure character(len=:) function, allocatable, public adjustc (string, length)
NAME
adjustc(3f) - [M_strings:WHITESPACE] center text (LICENSE:PD)
character(len=len(str)) function, public compact (str, char)
NAME
compact(3f) - [M_strings:WHITESPACE] converts contiguous whitespace to a single character (or nothing) (LICENSE:PD)
doubleprecision function, public s2v (chars, ierr, onerr)
NAME
s2v(3f) - [M_strings:NUMERIC] function returns doubleprecision numeric value from a string (LICENSE:PD)
subroutine, public split (input_line, array, delimiters, order, nulls)
NAME
split(3f) - [M_strings:TOKENS] parse string into an array using specified delimiters (LICENSE:PD)
subroutine, public string_to_values (line, iread, values, inums, delims, ierr)
NAME
string_to_values(3f) - [M_strings:NUMERIC] read a string representing numbers into a numeric array (LICENSE:PD)
pure character(len=len(instr)) function, public transliterate (instr, old_set, new_set)
NAME
transliterate(3f) - [M_strings:EDITING] replace characters from old set with new set (LICENSE:PD)
character(len=:) function, allocatable d2s (dvalue, fmt)
NAME
v2s(3f) - [M_strings:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
character(len=:) function, allocatable r2s (rvalue, fmt)
character(len=:) function, allocatable i2s (ivalue, fmt)
character(len=:) function, allocatable l2s (lvalue, fmt)
subroutine value_to_string (gval, chars, length, err, fmt, trimz)
NAME
value_to_string(3f) - [M_strings:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
subroutine trimzeros (string)
NAME
trimzeros(3fp) - [M_strings:NUMERIC] Delete trailing zeros from numeric decimal string (LICENSE:PD)
SYNOPSIS
subroutine a2r (chars, valu, ierr)
NAME
string_to_value(3f) - [M_strings:NUMERIC] subroutine returns numeric value from string (LICENSE:PD)
subroutine a2i (chars, valu, ierr)
subroutine a2d (chars, valu, ierr, onerr)
logical function decodebase (string, basein, out_baseten)
NAME
Function/Subroutine Documentation
a2d()
subroutine m_time_duplicate::a2d (character(len=*), intent(in) chars, doubleprecision, intent(out) valu, integer, intent(out) ierr, class(*), intent(in), optional onerr)
References decodebase(), stderr(), and substitute().
a2i()
subroutine m_time_duplicate::a2i (character(len=*), intent(in) chars, integer, intent(out) valu, integer, intent(out) ierr)
References a2d(), and stderr().
a2r()
subroutine m_time_duplicate::a2r (character(len=*), intent(in) chars, real, intent(out) valu, integer, intent(out) ierr)
NAME
string_to_value(3f) - [M_strings:NUMERIC] subroutine returns numeric value from string (LICENSE:PD)
SYNOPSIS
subroutine string_to_value(chars,valu,ierr)
 character(len=*),intent(in)              :: chars   ! input string
 integer|real|doubleprecision,intent(out) :: valu
 integer,intent(out)                      :: ierr
DESCRIPTION
returns a numeric value from a numeric character string.
works with any g-format input, including integer, real, and exponential. If the input string begins with "B", "Z", or "O" and otherwise represents a positive whole number it is assumed to be a binary, hexadecimal, or octal value. If the string contains commas they are removed. If the string is of the form NN:MMM... or NN::MMM then NN is assumed to be the base of the whole number.
if an error occurs in the READ, IOSTAT is returned in IERR and value is set to zero. if no error occurs, IERR=0.
OPTIONS
CHARS input string to read numeric value from
RETURNS
VALU numeric value returned. May be INTEGER, REAL, or DOUBLEPRECISION. IERR error flag (0 == no error)
EXAMPLE
Sample Program:
 program demo_string_to_value
 use M_strings, only: string_to_value
 character(len=80) :: string
    string=' -40.5e-2 '
    call string_to_value(string,value,ierr)
    write(*,*) 'value of string ['//trim(string)//'] is ',value
 end program demo_string_to_value
AUTHOR
John S. Urban
LICENSE
Public Domain
References a2d(), and stderr().
adjustc()
pure character(len=:) function, allocatable, public m_time_duplicate::adjustc (character(len=*), intent(in) string, integer, intent(in), optional length)
NAME
adjustc(3f) - [M_strings:WHITESPACE] center text (LICENSE:PD)
SYNOPSIS
pure function adjustc(string[,length])
character(len=*),intent(in) :: string integer,intent(in),optional :: length character(len=:),allocatable :: adjustc
DESCRIPTION
Centers input text in a string of the length specified. Returns a string of length LENGTH if LENGTH is present. Otherwise returns a string of the length of the input string.
OPTIONS
string input string to trim and center length line length to center text in, optional.
RETURNS
adjustc centered output string
EXAMPLES
Sample Program:
 program demo_adjustc
 use M_strings, only : adjustc
 !  using length of the input string
    write(*,'(a)')       '================================'
    write(*,'(a)')adjustc('centered string                 ')
    write(*,'(a)')adjustc('                 centered string')
    write(*,'(a)')adjustc('  centered string               ')
 !  using explicit output string length
    write(*,'(a)')repeat('=',50)
    write(*,'(a)')adjustc('this is a centered string',50)
    write(*,'(a)')repeat('=',50)
 end program demo_adjustc
Expected output:
 \================================
         centered string
         centered string
         centered string
 \==================================================
             this is a centered string
 \==================================================
AUTHOR
John S. Urban
LICENSE
Public Domain
Parameters
[in] string PROCEDURE adjustc(3f) DESCRIPTION center text using implicit or explicit length
VERSION 2.0, 20160711
AUTHOR John S. Urban
compact()
character(len=len(str)) function, public m_time_duplicate::compact (character(len=*), intent(in) str, character(len=*), intent(in), optional char)
NAME
compact(3f) - [M_strings:WHITESPACE] converts contiguous whitespace to a single character (or nothing) (LICENSE:PD)
SYNOPSIS
function compact(STR,CHAR) result (OUTSTR)
 character(len=*),intent(in)          :: STR
 character(len=*),intent(in),optional :: CHAR
 character(len=len(str))              :: OUTSTR
DESCRIPTION
COMPACT(3f) converts multiple spaces, tabs and control characters (called "whitespace") to a single character or nothing. Leading whitespace is removed.
OPTIONS
STR input string to reduce or remove whitespace from CHAR By default the character that replaces adjacent whitespace is a space. If the optional CHAR parameter is supplied it will be used to replace the whitespace. If a null character is supplied for CHAR whitespace is removed.
RETURNS
OUTSTR string of same length as input string but with all contiguous whitespace reduced to a single space and leading whitespace removed
EXAMPLES
Sample Program:
 program demo_compact
 use M_strings, only : compact
 implicit none
 ! produces 'This is a test               '
 write(*,*)compact('  This     is      a     test  ')
 ! produces 'Thisisatest                  '
 write(*,*)compact('  This     is      a     test  ',char='')
 ! produces 'This:is:a:test               '
 write(*,*)compact('  This     is      a     test  ',char=':')
 ! note CHAR is used to replace the whitespace, but if CHAR is
 ! in the original string it is just copied
 write(*,*)compact('A  AA    A   AAAAA',char='A')
 ! produces (original A characters are left as-is) 'AAAAAAAAAAAA'
 ! not 'A'
 end program demo_compact
Expected output
 >This is a test
 >Thisisatest
 >This:is:a:test
 >AAAAAAAAAAAA
AUTHOR
John S. Urban
LICENSE
Public Domain
d2s()
character(len=:) function, allocatable m_time_duplicate::d2s (doubleprecision, intent(in) dvalue, character(len=*), intent(in), optional fmt)
NAME
v2s(3f) - [M_strings:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
SYNOPSIS
   function v2s(value) result(outstr)
    integer|real|doubleprecision|logical,intent(in ) :: value
    character(len=:),allocatable :: outstr
    character(len=*),optional,intent(in) :: fmt
DESCRIPTION
v2s(3f) returns a representation of a numeric value as a string when given a numeric value of type REAL, DOUBLEPRECISION, INTEGER or LOGICAL. It creates the strings using internal WRITE() statements. Trailing zeros are removed from non-zero values, and the string is left-justified.
OPTIONS
VALUE input value to be converted to a string FMT format can be explicitly given, but is limited to generating a string of eighty or less characters.
RETURNS
OUTSTR returned string representing input value,
EXAMPLE
Sample Program:
 program demo_v2s
 use M_strings, only: v2s
 write(*,*) 'The value of 3.0/4.0 is ['//v2s(3.0/4.0)//']'
 write(*,*) 'The value of 1234    is ['//v2s(1234)//']'
 write(*,*) 'The value of 0d0     is ['//v2s(0d0)//']'
 write(*,*) 'The value of .false. is ['//v2s(.false.)//']'
 write(*,*) 'The value of .true. is  ['//v2s(.true.)//']'
 end program demo_v2s
Expected output
 The value of 3.0/4.0 is [0.75]
 The value of 1234    is [1234]
 The value of 0d0     is [0]
 The value of .false. is [F]
 The value of .true. is  [T]
AUTHOR
John S. Urban
LICENSE
Public Domain
References value_to_string().
decodebase()
logical function m_time_duplicate::decodebase (character(len=*), intent(in) string, integer, intent(in) basein, integer, intent(out) out_baseten)
NAME
decodebase(3f) - [M_strings:BASE] convert whole number string in base [2-36] to base 10 number (LICENSE:PD)
SYNOPSIS
logical function decodebase(string,basein,out10)
 character(len=*),intent(in)  :: string
 integer,intent(in)           :: basein
 integer,intent(out)          :: out10
DESCRIPTION
Convert a numeric string representing a whole number in base BASEIN to base 10. The function returns FALSE if BASEIN is not in the range [2..36] or if string STRING contains invalid characters in base BASEIN or if result OUT10 is too big
The letters A,B,...,Z represent 10,11,...,36 in the base > 10.
OPTIONS
string input string. It represents a whole number in the base specified by BASEIN unless BASEIN is set to zero. When BASEIN is zero STRING is assumed to be of the form BASE::VALUE where BASE represents the function normally provided by BASEIN. basein base of input string; either 0 or from 2 to 36. out10 output value in base 10
EXAMPLE
Sample program:
 program demo_decodebase
 use M_strings, only : codebase, decodebase
 implicit none
 integer           :: ba,bd
 character(len=40) :: x,y
 integer           :: r
 print *,' BASE CONVERSION'
 write(*,'("Start   Base (2 to 36): ")',advance='no'); read *, bd
 write(*,'("Arrival Base (2 to 36): ")',advance='no'); read *, ba
 INFINITE: do
    print *,''
    write(*,'("Enter number in start base: ")',advance='no'); read *, x
    if(x.eq.'0') exit INFINITE
    if(decodebase(x,bd,r)) then
       if(codebase(r,ba,y)) then
         write(*,'("In base ",I2,": ",A20)')  ba, y
       else
         print *,'Error in coding number.'
       endif
    else
       print *,'Error in decoding number.'
    endif
 enddo INFINITE
 end program demo_decodebase
AUTHOR
John S. Urban
Ref.: "Math matiques en Turbo-Pascal by M. Ducamp and A. Reverchon (2), Eyrolles, Paris, 1988".
based on a F90 Version By J-P Moreau (www.jpmoreau.fr)
LICENSE
Public Domain
References upper().
i2s()
character(len=:) function, allocatable m_time_duplicate::i2s (integer, intent(in) ivalue, character(len=*), intent(in), optional fmt)
References value_to_string().
l2s()
character(len=:) function, allocatable m_time_duplicate::l2s (logical, intent(in) lvalue, character(len=*), intent(in), optional fmt)
References value_to_string().
lower()
elemental pure character(len(str)) function, public m_time_duplicate::lower (character(*), intent(in) str, integer, intent(in), optional begin, integer, intent(in), optional end)
NAME
lower(3f) - [M_strings:CASE] changes a string to lowercase over specified range (LICENSE:PD)
SYNOPSIS
elemental pure function lower(str,begin,end) result (string)
 character(*), intent(in) :: str
 integer,optional         :: begin, end
 character(len(str))      :: string  ! output string
DESCRIPTION
lower(string) returns a copy of the input string with all characters converted to miniscule over the specified range, assuming ASCII character sets are being used. If no range is specified the entire string is converted to miniscule.
OPTIONS
str string to convert to miniscule begin optional starting position in "str" to begin converting to miniscule end optional ending position in "str" to stop converting to miniscule
RESULTS
lower copy of the input string with all characters converted to miniscule over optionally specified range.
TRIVIA
The terms "uppercase" and "lowercase" date back to the early days of the mechanical printing press. Individual metal alloy casts of each needed letter, or punctuation symbol, were meticulously added to a press block, by hand, before rolling out copies of a page. These metal casts were stored and organized in wooden cases. The more often needed miniscule letters were placed closer to hand, in the lower cases of the work bench. The less often needed, capitalized, majuscule letters, ended up in the harder to reach upper cases.
EXAMPLE
Sample program:
 program demo_lower
 use M_time, only: lower
 implicit none
 character(len=:),allocatable  :: s
    s=' ABCDEFG abcdefg '
    write(*,*) 'mixed-case input string is ....',s
    write(*,*) 'lower-case output string is ...',lower(s)
 end program demo_lower
Expected output
   mixed-case input string is .... ABCDEFG abcdefg
   lower-case output string is ... abcdefg abcdefg
AUTHOR
John S. Urban
LICENSE
Public Domain
r2s()
character(len=:) function, allocatable m_time_duplicate::r2s (real, intent(in) rvalue, character(len=*), intent(in), optional fmt)
References value_to_string().
s2v()
doubleprecision function, public m_time_duplicate::s2v (character(len=*), intent(in) chars, integer, optional ierr, class(*), intent(in), optional onerr)
NAME
s2v(3f) - [M_strings:NUMERIC] function returns doubleprecision numeric value from a string (LICENSE:PD)
SYNOPSIS
function s2v(string[,ierr][,onerr])
 character(len=*)             :: string
 doubleprecision              :: s2v
 integer,intent(out),optional :: ierr
 class(*),intent(in),optional :: onerr
DESCRIPTION
This function converts a string to a DOUBLEPRECISION numeric value.
The intrinsics INT(3f), REAL(3f), and DBLE(3f) are also extended to take CHARACTER variables. The KIND= keyword is not supported on the extensions.
OPTIONS
 string   holds string assumed to represent a numeric value
 ierr     If an error occurs the program is stopped if the optional
          parameter IERR is not present. If IERR returns a non-zero
          value an error occurred.
 onerr    The value to return on error. A value of zero (NaN) is
          returned on error by default.
RETURNS
s2v
EXAMPLE
Sample Program:
 program demo_s2v
 use M_strings, only: s2v, int, real, dble
 implicit none
 character(len=8)              :: s=' 10.345 '
 integer                       :: i
 character(len=14),allocatable :: strings(:)
 doubleprecision               :: dv
 integer                       :: errnum
 ! different strings representing INTEGER, REAL, and DOUBLEPRECISION
 strings=[&
 &' 10.345       ',&
 &'+10           ',&
 &'    -3        ',&
 &'    -4.94e-2  ',&
 &'0.1           ',&
 &'12345.678910d0',&
 &'              ',& ! Note: will return zero without an error message
 &'1 2 1 2 1 . 0 ',& ! Note: spaces will be ignored
 &'WHAT?         ']  ! Note: error messages will appear, zero returned
 ! a numeric value is returned, so it can be used in numeric expression
 write(*,*) '1/2 value of string is ',s2v(s)/2.0d0
 write(*,*)
 write(*,*)' STRING            VALUE                    ERROR_NUMBER'
 do i=1,size(strings)
    ! Note: not a good idea to use s2v(3f) in a WRITE(3f) statement,
    ! as it does I/O when errors occur, so called on a separate line
    dv=s2v(strings(i),errnum)
    write(*,*) strings(i)//'=',dv,errnum
 enddo
 write(*,*)"Extended intrinsics"
 write(*,*)'given inputs:',s,strings(:8)
 write(*,*)'INT(3f):',int(s),int(strings(:8))
 write(*,*)'REAL(3f):',real(s),real(strings(:8))
 write(*,*)'DBLE(3f):',dble(s),dble(strings(:8))
 write(*,*)"That's all folks!"
 end program demo_s2v
Expected output
 >1/2 value of string is    5.1725000000000003
 >
 > STRING            VALUE                    ERROR_NUMBER
 > 10.345       =   10.345000000000001                0
 >+10           =   10.000000000000000                0
 >    -3        =  -3.0000000000000000                0
 >    -4.94e-2  =  -4.9399999999999999E-002           0
 >0.1           =  0.10000000000000001                0
 >12345.678910d0=   12345.678910000001                0
 >              =   0.0000000000000000                0
 >1 2 1 2 1 . 0 =   12121.000000000000                0
 >*a2d* - cannot produce number from string [WHAT?]
 >*a2d* - [Bad value during floating point read]
 >WHAT?         =   0.0000000000000000             5010
 >Extended intrinsics
 >given inputs: 10.345 10.345 +10 -3 -4.94e-2 0.1 12345.678910d0 1 2 1 2 1 . 0
 >INT(3f): 10 10 10 -3 0 0 12345 0 12121
 >REAL(3f): 10.3450003 10.3450003 10.0000000 -3.00000000 -4.94000018E-02
 >          0.100000001 12345.6787 0.00000000 12121.0000
 >DBLE(3f): 10.345000000000001 10.345000000000001 10.000000000000000
 >          -3.0000000000000000 -4.9399999999999999E-002 0.10000000000000001
 >          12345.678910000001 0.0000000000000000 12121.000000000000
 >That's all folks!
AUTHOR
John S. Urban
LICENSE
Public Domain
PROCEDURE:
DESCRIPTION: s2v(3f): function returns doubleprecision number from string;zero if error occurs
VERSION: 2.0, 20160704
AUTHOR: John S. Urban
References a2d().
split()
subroutine, public m_time_duplicate::split (character(len=*), intent(in) input_line, character(len=:), dimension(:), intent(out), allocatable array, character(len=*), intent(in), optional delimiters, character(len=*), intent(in), optional order, character(len=*), intent(in), optional nulls)
NAME
split(3f) - [M_strings:TOKENS] parse string into an array using specified delimiters (LICENSE:PD)
SYNOPSIS
subroutine split(input_line,array,delimiters,order,nulls)
 character(len=*),intent(in)              :: input_line
 character(len=:),allocatable,intent(out) :: array(:)
 character(len=*),optional,intent(in)     :: delimiters
 character(len=*),optional,intent(in)     :: order
 character(len=*),optional,intent(in)     :: nulls
DESCRIPTION
SPLIT(3f) parses a string using specified delimiter characters and store tokens into an allocatable array
OPTIONS
INPUT_LINE  Input string to tokenize
ARRAY       Output array of tokens
DELIMITERS  List of delimiter characters.
            The default delimiters are the "whitespace" characters
            (space, tab,new line, vertical tab, formfeed, carriage
            return, and null). You may specify an alternate set of
            delimiter characters.
            Multi-character delimiters are not supported (Each
            character in the DELIMITERS list is considered to be
            a delimiter).
            Quoting of delimiter characters is not supported.
ORDER SEQUENTIAL|REVERSE|RIGHT  Order of output array.
            By default ARRAY contains the tokens having parsed
            the INPUT_LINE from left to right. If ORDER='RIGHT'
            or ORDER='REVERSE' the parsing goes from right to left.
NULLS IGNORE|RETURN|IGNOREEND  Treatment of null fields.
            By default adjacent delimiters in the input string
            do not create an empty string in the output array. if
            NULLS='return' adjacent delimiters create an empty element
            in the output ARRAY. If NULLS='ignoreend' then only
            trailing delimiters at the right of the string are ignored.
EXAMPLES
Sample program:
 program demo_split
 use M_strings, only: split
 character(len=*),parameter     :: &
 & line='  aBcdef   ghijklmnop qrstuvwxyz  1:|:2     333|333 a B cc    '
 character(len=:),allocatable :: array(:) ! output array of tokens
    write(*,*)'INPUT LINE:['//LINE//']'
    write(*,'(80("="))')
    write(*,*)'typical call:'
    CALL split(line,array)
    write(*,'(i0," ==> ",a)')(i,trim(array(i)),i=1,size(array))
    write(*,*)'SIZE:',SIZE(array)
    write(*,'(80("-"))')
    write(*,*)'custom list of delimiters (colon and vertical line):'
    CALL split(line,array,delimiters=':|',order='sequential',nulls='ignore')
    write(*,'(i0," ==> ",a)')(i,trim(array(i)),i=1,size(array))
    write(*,*)'SIZE:',SIZE(array)
    write(*,'(80("-"))')
    write(*,*)&
    &'custom list of delimiters, reverse array order and count null fields:'
    CALL split(line,array,delimiters=':|',order='reverse',nulls='return')
    write(*,'(i0," ==> ",a)')(i,trim(array(i)),i=1,size(array))
    write(*,*)'SIZE:',SIZE(array)
    write(*,'(80("-"))')
    write(*,*)'INPUT LINE:['//LINE//']'
    write(*,*)&
    &'default delimiters and reverse array order and return null fields:'
    CALL split(line,array,delimiters='',order='reverse',nulls='return')
    write(*,'(i0," ==> ",a)')(i,trim(array(i)),i=1,size(array))
    write(*,*)'SIZE:',SIZE(array)
end program demo_split
Output
 > INPUT LINE:[  aBcdef   ghijklmnop qrstuvwxyz  1:|:2     333|333 a B cc    ]
 > ===========================================================================
 >  typical call:
 > 1 ==> aBcdef
 > 2 ==> ghijklmnop
 > 3 ==> qrstuvwxyz
 > 4 ==> 1:|:2
 > 5 ==> 333|333
 > 6 ==> a
 > 7 ==> B
 > 8 ==> cc
 >  SIZE:           8
 > --------------------------------------------------------------------------
 >  custom list of delimiters (colon and vertical line):
 > 1 ==>   aBcdef   ghijklmnop qrstuvwxyz  1
 > 2 ==> 2     333
 > 3 ==> 333 a B cc
 >  SIZE:           3
 > --------------------------------------------------------------------------
 >  custom list of delimiters, reverse array order and return null fields:
 > 1 ==> 333 a B cc
 > 2 ==> 2     333
 > 3 ==>
 > 4 ==>
 > 5 ==>   aBcdef   ghijklmnop qrstuvwxyz  1
 >  SIZE:           5
 > --------------------------------------------------------------------------
 >  INPUT LINE:[  aBcdef   ghijklmnop qrstuvwxyz  1:|:2     333|333 a B cc    ]
 >  default delimiters and reverse array order and count null fields:
 > 1 ==>
 > 2 ==>
 > 3 ==>
 > 4 ==> cc
 > 5 ==> B
 > 6 ==> a
 > 7 ==> 333|333
 > 8 ==>
 > 9 ==>
 > 10 ==>
 > 11 ==>
 > 12 ==> 1:|:2
 > 13 ==>
 > 14 ==> qrstuvwxyz
 > 15 ==> ghijklmnop
 > 16 ==>
 > 17 ==>
 > 18 ==> aBcdef
 > 19 ==>
 > 20 ==>
 >  SIZE:          20
AUTHOR
John S. Urban
LICENSE
Public Domain
References lower().
stderr()
subroutine m_time_duplicate::stderr (character(len=*) string)
string_to_values()
subroutine, public m_time_duplicate::string_to_values (character(len=*), intent(in) line, integer, intent(in) iread, real, dimension(iread), intent(inout) values, integer, intent(out) inums, character(len=*), intent(in) delims, integer, intent(out) ierr)
NAME
string_to_values(3f) - [M_strings:NUMERIC] read a string representing numbers into a numeric array (LICENSE:PD)
SYNOPSIS
   subroutine string_to_values(line,iread,values,inums,delims,ierr)
    character(len=*) :: line
    integer          :: iread
    real             :: values(*)
    integer          :: inums
    character(len=*) :: delims
    integer          :: ierr
DESCRIPTION
This routine can take a string representing a series of numbers and convert it to a numeric array and return how many numbers were found.
OPTIONS
   LINE     Input string containing numbers
   IREAD    maximum number of values to try to read from input string
RESULTS
   VALUES   real array to be filled with numbers
   INUMS    number of values successfully read (before error occurs
            if one does)
   DELIMS   delimiter character(s), usually a space. must not be a
            null string. If more than one character, a space must
            not be the last character or it will be ignored.
   IERR     error flag (0=no error, else column number string starts
            at that error occurred on).
EXAMPLE
Sample Program:
 program demo_string_to_values
  use M_strings, only : string_to_values
  character(len=80)  :: s=' 10 20e3;3.45 -400.3e-2;1234; 5678 '
  integer,parameter  :: isz=10
  real               :: array(isz)
  call string_to_values(s,10,array,inums,' ;',ierr)
  call reportit()
  call string_to_values('10;2.3;3.1416',isz,array,inums,' ;',ierr)
  call reportit()
  contains
     subroutine reportit()
        write(*,*)'string_to_values:'
        write(*,*)'input string.............',trim(s)
        write(*,*)'number of values found...',inums
        write(*,*)'values...................',(array(ii),ii=1,inums)
     end subroutine reportit
 end program demo_string_to_values
Expected output
string_to_values:
input string............. 10 20e3;3.45 -400.3e-2;1234; 5678
number of values found...           6
values...................   10.0000000  20000.0000  3.45000005  -4.00299978  1234.00000  5678.00000
string_to_values:
input string............. 10 20e3;3.45 -400.3e-2;1234; 5678
number of values found...           3
values...................   10.0000000  2.29999995  3.14159989
AUTHOR
John S. Urban
LICENSE
Public Domain
References stderr().
substitute()
subroutine, public m_time_duplicate::substitute (character(len=*) targetline, character(len=*), intent(in) old, character(len=*), intent(in) new, integer, intent(out), optional ierr, integer, intent(in), optional start, integer, intent(in), optional end)
NAME
substitute(3f) - [M_strings:EDITING] subroutine globally substitutes one substring for another in string (LICENSE:PD)
SYNOPSIS
subroutine substitute(targetline,old,new,ierr,start,end)
 character(len=*)              :: targetline
 character(len=*),intent(in)   :: old
 character(len=*),intent(in)   :: new
 integer,intent(out),optional  :: ierr
 integer,intent(in),optional   :: start
 integer,intent(in),optional   :: end
DESCRIPTION
Globally substitute one substring for another in string.
OPTIONS
TARGETLINE input line to be changed. Must be long enough to hold altered output. OLD substring to find and replace NEW replacement for OLD substring IERR error code. If IER = -1 bad directive, >= 0 then count of changes made. START sets the left margin to be scanned for OLD in TARGETLINE. END sets the right margin to be scanned for OLD in TARGETLINE.
EXAMPLES
Sample Program:
 program demo_substitute
 use M_time, only : substitute
 implicit none
 ! must be long enough to hold changed line
 character(len=80) :: targetline
 targetline='this is the input string'
 write(*,*)'ORIGINAL    : '//trim(targetline)
 ! changes the input to 'THis is THe input string'
 call substitute(targetline,'th','TH')
 write(*,*)'th => TH    : '//trim(targetline)
 ! a null old substring means "at beginning of line"
 ! changes the input to 'BEFORE:this is the input string'
 call substitute(targetline,'','BEFORE:')
 write(*,*)'"" => BEFORE: '//trim(targetline)
 ! a null new string deletes occurrences of the old substring
 ! changes the input to 'ths s the nput strng'
 call substitute(targetline,'i','')
 write(*,*)'i => ""     : '//trim(targetline)
 end program demo_substitute
Expected output
 ORIGINAL    : this is the input string
 th => TH    : THis is THe input string
 "" => BEFORE: BEFORE:THis is THe input string
 i => ""     : BEFORE:THs s THe nput strng
AUTHOR
John S. Urban
LICENSE
Public Domain
References stderr().
transliterate()
pure character(len=len(instr)) function, public m_time_duplicate::transliterate (character(len=*), intent(in) instr, character(len=*), intent(in) old_set, character(len=*), intent(in) new_set)
NAME
transliterate(3f) - [M_strings:EDITING] replace characters from old set with new set (LICENSE:PD)
SYNOPSIS
pure function transliterate(instr,old_set,new_set) result(outstr)
 character(len=*),intent(in)  :: instr
 character(len=*),intent(in)  :: old_set
 character(len=*),intent(in)  :: new_set
 character(len=len(instr))    :: outstr
DESCRIPTION
Translate, squeeze, and/or delete characters from the input string.
OPTIONS
instr input string to change old_set list of letters to change in INSTR if found
     Each character in the input string that matches a character in
     the old set is replaced.
new_set list of letters to replace letters in OLD_SET with.
     If the new_set is the empty set the matched characters are deleted.
     If the new_set is shorter than the old set the last character in the
     new set is used to replace the remaining characters in the new set.
RETURNS
outstr instr with substitutions applied
EXAMPLES
Sample Program:
 program demo_transliterate
 use M_strings, only : transliterate
 implicit none
 character(len=80)   :: STRING
 STRING='aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ'
 write(*,'(a)') STRING
 ! convert a string to uppercase:
 write(*,*) TRANSLITERATE(STRING,'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ')
 ! change all miniscule letters to a colon (":"):
 write(*,*) TRANSLITERATE(STRING,'abcdefghijklmnopqrstuvwxyz',':')
 ! delete all miniscule letters
 write(*,*) TRANSLITERATE(STRING,'abcdefghijklmnopqrstuvwxyz','')
 end program demo_transliterate
Expected output
 > aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ
 > AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZ
 > :A:B:C:D:E:F:G:H:I:J:K:L:M:N:O:P:Q:R:S:T:U:V:W:X:Y:Z
 > ABCDEFGHIJKLMNOPQRSTUVWXYZ
AUTHOR
John S. Urban
LICENSE
Public Domain
trimzeros()
subroutine m_time_duplicate::trimzeros (character(len=*) string)
NAME
trimzeros(3fp) - [M_strings:NUMERIC] Delete trailing zeros from numeric decimal string (LICENSE:PD)
SYNOPSIS
subroutine trimzeros(str)
character(len=*) :: str
DESCRIPTION
TRIMZEROS(3f) deletes trailing zeros from a string representing a number. If the resulting string would end in a decimal point, one trailing zero is added.
OPTIONS
str input string will be assumed to be a numeric value and have trailing zeros removed
EXAMPLES
Sample program:
   program demo_trimzeros
   use M_strings, only : trimzeros
   character(len=:),allocatable :: string
      write(*,*)trimzeros('123.450000000000')
      write(*,*)trimzeros('12345')
      write(*,*)trimzeros('12345.')
      write(*,*)trimzeros('12345.00e3')
   end program demo_trimzeros
AUTHOR
John S. Urban
LICENSE
Public Domain
upper()
elemental pure character(len(str)) function, public m_time_duplicate::upper (character(*), intent(in) str, integer, intent(in), optional begin, integer, intent(in), optional end)
NAME
upper(3f) - [M_strings:CASE] changes a string to uppercase (LICENSE:PD)
SYNOPSIS
elemental pure function upper(str,begin,end) result (string)
 character(*), intent(in)    :: str
 integer,optional,intent(in) :: begin,end
 character(len(str))         :: string  ! output string
DESCRIPTION
upper(string) returns a copy of the input string with all characters converted in the optionally specified range to uppercase, assuming ASCII character sets are being used. If no range is specified the entire string is converted to uppercase.
OPTIONS
str string to convert to uppercase begin optional starting position in "str" to begin converting to uppercase end optional ending position in "str" to stop converting to uppercase
RESULTS
upper copy of the input string with all characters converted to uppercase over optionally specified range.
TRIVIA
The terms "uppercase" and "lowercase" date back to the early days of the mechanical printing press. Individual metal alloy casts of each needed letter, or punctuation symbol, were meticulously added to a press block, by hand, before rolling out copies of a page. These metal casts were stored and organized in wooden cases. The more often needed miniscule letters were placed closer to hand, in the lower cases of the work bench. The less often needed, capitalized, majuscule letters, ended up in the harder to reach upper cases.
EXAMPLE
Sample program:
 program demo_upper
 use M_time, only: upper
 implicit none
 character(len=:),allocatable  :: s
    s=' ABCDEFG abcdefg '
    write(*,*) 'mixed-case input string is ....',s
    write(*,*) 'upper-case output string is ...',upper(s)
    write(*,*) 'make first character uppercase  ... ',upper('this is a sentence.',1,1)
    write(*,'(1x,a,*(a:,"+"))') 'upper(3f) is elemental ==>',upper(["abc","def","ghi"])
 end program demo_upper
Expected output
 mixed-case input string is .... ABCDEFG abcdefg
 upper-case output string is ... ABCDEFG ABCDEFG
 make first character uppercase  ... This is a sentence.
 upper(3f) is elemental ==>ABC+DEF+GHI
AUTHOR
John S. Urban
LICENSE
Public Domain
value_to_string()
subroutine m_time_duplicate::value_to_string (class(*), intent(in) gval, character(len=*), intent(out) chars, integer, intent(out), optional length, integer, optional err, character(len=*), intent(in), optional fmt, logical, intent(in), optional trimz)
NAME
value_to_string(3f) - [M_strings:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
SYNOPSIS
subroutine value_to_string(value,chars[,ilen,ierr,fmt,trimz])
 character(len=*) :: chars  ! minimum of 23 characters required
 !--------
 ! VALUE may be any <em>one</em> of the following types:
 doubleprecision,intent(in)               :: value
 real,intent(in)                          :: value
 integer,intent(in)                       :: value
 logical,intent(in)                       :: value
 !--------
 character(len=*),intent(out)             :: chars
 integer,intent(out),optional             :: ilen
 integer,optional                         :: ierr
 character(len=*),intent(in),optional     :: fmt
 logical,intent(in)                       :: trimz
DESCRIPTION
value_to_string(3f) returns a numeric representation of a numeric value in a string given a numeric value of type REAL, DOUBLEPRECISION, INTEGER or LOGICAL. It creates the string using internal writes. It then removes trailing zeros from non-zero values, and left-justifies the string.
OPTIONS
VALUE input value to be converted to a string FMT You may specify a specific format that produces a string up to the length of CHARS; optional. TRIMZ If a format is supplied the default is not to try to trim trailing zeros. Set TRIMZ to .true. to trim zeros from a string assumed to represent a simple numeric value.
RETURNS
CHARS returned string representing input value, must be at least 23 characters long; or what is required by optional FMT if longer. ILEN position of last non-blank character in returned string; optional. IERR If not zero, error occurred; optional.
EXAMPLE
Sample program:
  program demo_value_to_string
  use M_strings, only: value_to_string
  implicit none
  character(len=80) :: string
  integer           :: ilen
     call value_to_string(3.0/4.0,string,ilen)
     write(*,*) 'The value is [',string(:ilen),']'
     call value_to_string(3.0/4.0,string,ilen,fmt='')
     write(*,*) 'The value is [',string(:ilen),']'
     call value_to_string(3.0/4.0,string,ilen,fmt='("THE VALUE IS ",g0)')
     write(*,*) 'The value is [',string(:ilen),']'
     call value_to_string(1234,string,ilen)
     write(*,*) 'The value is [',string(:ilen),']'
     call value_to_string(1.0d0/3.0d0,string,ilen)
     write(*,*) 'The value is [',string(:ilen),']'
  end program demo_value_to_string
Expected output
 The value is [0.75]
 The value is [      0.7500000000]
 The value is [THE VALUE IS .750000000]
 The value is [1234]
 The value is [0.33333333333333331]
AUTHOR
John S. Urban
LICENSE
Public Domain
References stderr(), and trimzeros().