M_time: m_time Module Reference
m_time Module Reference
Data Types
interface date_time
interface string_to_value
interface v2s
Functions/Subroutines
subroutine, public date_to_julian (dat, julian, ierr)
NAME
date_to_julian(3f) - [M_time] converts DAT date-time array to Julian Date (LICENSE:PD)
subroutine, public julian_to_date (julian, dat, ierr)
NAME
julian_to_date(3f) - [M_time] converts a JED(Julian Ephemeris Date) to a DAT date-time array. (LICENSE:PD)
subroutine, public date_to_unix (dat, unixtime, ierr)
NAME
date_to_unix(3f) - [M_time] converts DAT date-time array to Unix Epoch Time (LICENSE:PD)
subroutine, public unix_to_date (unixtime, dat, ierr)
NAME
unix_to_date(3f) - [M_time] converts Unix Epoch Time to DAT date-time array (LICENSE:PD)
integer function, public d2o (dat)
NAME
d2o(3f) - [M_time] converts DAT date-time array to Ordinal day (LICENSE:PD)
integer function, public ordinal_seconds ()
NAME
ordinal_seconds(3f) - [M_time] seconds since beginning of year (LICENSE:PD)
SYNOPSIS
subroutine, public ordinal_to_date (yyyy, ddd, dat)
NAME
ordinal_to_date(3f) - [M_time] when given a valid year and day of the year returns the DAT array for the date (LICENSE:PD)
SYNOPSIS
integer function, dimension(8), public o2d (ordinal, year)
NAME
o2d(3f) - [M_time] converts Ordinal day to DAT date-time array (LICENSE:PD)
character(len=:) function, allocatable, public v2mo (imonth)
NAME
v2mo(3f) - [M_time] returns the month name of a Common month number (LICENSE:PD)
integer function, dimension(8), public mo2d (month_name, year)
NAME
mo2d(3f) - [M_time] given month name return DAT date-time array for beginning of that month in specified year (LICENSE:PD)
integer function, public mo2v (month_name)
NAME
mo2v(3f) - [M_time] given month name return month number (1-12) of that month (LICENSE:PD)
character(len=:) function, allocatable, public now (format)
NAME
now(3f) - [M_time] return string representing current time given format (LICENSE:PD)
character(len=:) function, allocatable, public fmtdate (values, format)
NAME
fmtdate(3f) - [M_time] given DAT date-time array return date as string using specified format (LICENSE:PD)
subroutine, public fmtdate_usage (indent)
NAME
fmtdate_usage(3f) - [M_time] display macros recognized by fmtdate(3f) and now(3f) (LICENSE:PD)
subroutine, public guessdate (datestring, dat, ier)
NAME
guessdate(3f) - [M_time] reads in a date, in various formats (LICENSE:PD)
subroutine, public dow (values, weekday, day, ierr)
NAME
dow(3f) - [M_time] given a date-time array DAT return the day of the week (LICENSE:PD)
subroutine, public d2w (dat, iso_year, iso_week, iso_weekday, iso_name)
NAME
d2w(3f) - [M_time] calculate iso-8601 Week-numbering year date yyyy-Www-d given DAT date-time array (LICENSE:PD)
subroutine, public w2d (iso_year, iso_week, iso_weekday, dat)
NAME
w2d(3f) - [M_time] calculate DAT date-time array from iso-8601 Week-numbering year date yyyy-Www-d (LICENSE:PD)
subroutine, public box_month (dat, calen)
NAME
box_month(3f) - [M_time] create specified month in a character array (LICENSE:PD)
real(kind=realtime) function, public d2j (dat)
NAME
d2j(3f) - [M_time] given DAT date-time array returns Julian Date (LICENSE:PD)
integer function, dimension(8), public j2d (julian)
NAME
j2d(3f) - [M_time] given a JED (Julian Ephemeris Date) returns a date-time array DAT. (LICENSE:PD)
real(kind=realtime) function, public d2u (dat)
NAME
d2u(3f) - [M_time] given DAT date-time array returns Unix Epoch Time (UET starts at 0000 on 1 Jan. 1970, UTC) (LICENSE:PD)
integer function, dimension(8), public u2d (unixtime)
NAME
u2d(3f) - [M_time] given Unix Epoch Time returns DAT date-time array (LICENSE:PD)
integer function get_timezone ()
character(len=:) function, allocatable, public sec2days (seconds, crop)
NAME
sec2days(3f) - [M_time] convert seconds to string of form dd-hh:mm:ss (LICENSE:PD)
real(kind=realtime) function, public days2sec (str)
NAME
days2sec(3f) - [M_time] convert string of form [[-]dd-]hh:mm:ss.nn to seconds (LICENSE:PD)
character(len=:) function, allocatable, public phase_of_moon (datin)
NAME
phase_of_moon(3f) - [M_time] return name for phase of moon for given date (LICENSE:PD)
SYNOPSIS
integer function, public moon_fullness (datin)
NAME
moon_fullness(3f) - [M_time] return percentage of moon phase from new to full (LICENSE:PD)
SYNOPSIS
subroutine, public easter (year, dat)
NAME
easter(3f) - [M_time] calculate date for Easter given a year (LICENSE:PD)
subroutine, private substitute (targetline, old, new, ierr, start, end)
NAME
substitute(3f) - [M_strings:EDITING] subroutine globally substitutes one substring for another in string (LICENSE:PD)
elemental pure character(len(str)) function, private upper (str, begin, end)
NAME
upper(3f) - [M_strings:CASE] changes a string to uppercase (LICENSE:PD)
elemental pure character(len(str)) function, private lower (str, begin, end)
NAME
lower(3f) - [M_strings:CASE] changes a string to lowercase over specified range (LICENSE:PD)
subroutine stderr (string)
pure character(len=:) function, allocatable, private adjustc (string, length)
NAME
adjustc(3f) - [M_strings:WHITESPACE] center text (LICENSE:PD)
character(len=len(str)) function, private compact (str, char)
NAME
compact(3f) - [M_strings:WHITESPACE] converts contiguous whitespace to a single character (or nothing) (LICENSE:PD)
doubleprecision function, private s2v (chars, ierr, onerr)
NAME
s2v(3f) - [M_strings:NUMERIC] function returns doubleprecision numeric value from a string (LICENSE:PD)
subroutine, private split (input_line, array, delimiters, order, nulls)
NAME
split(3f) - [M_strings:TOKENS] parse string into an array using specified delimiters (LICENSE:PD)
subroutine, private string_to_values (line, iread, values, inums, delims, ierr)
NAME
string_to_values(3f) - [M_strings:NUMERIC] read a string representing numbers into a numeric array (LICENSE:PD)
pure character(len=len(instr)) function, private transliterate (instr, old_set, new_set)
NAME
transliterate(3f) - [M_strings:EDITING] replace characters from old set with new set (LICENSE:PD)
character(len=:) function, allocatable d2s (dvalue, fmt)
NAME
v2s(3f) - [M_strings:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
character(len=:) function, allocatable r2s (rvalue, fmt)
character(len=:) function, allocatable i2s (ivalue, fmt)
character(len=:) function, allocatable l2s (lvalue, fmt)
subroutine value_to_string (gval, chars, length, err, fmt, trimz)
NAME
value_to_string(3f) - [M_strings:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
type(date_time) function construct_from_dat (dat)
type(date_time) function construct_from_jed (jed)
type(date_time) function construct_from_uet (uet)
integer function, dimension(8), private dt2d (self)
real(kind=realtime) function, private epoch (self)
character(len=:) function, allocatable, private format (self, fmt)
real(kind=realtime) function, private julian_oop (self)
integer function, private ordinal_oop (self)
integer function, private weekday_oop (self)
type(date_time) function, private delta (self, year, month, day, tz, hour, minute, second, millisecond, week, duration)
subroutine, private init_dt (self, year, month, day, tz, hour, minute, second, millisecond, type, dat)
type(date_time) function plus_seconds (self, seconds)
type(date_time) function minus_seconds (self, seconds)
real(kind=realtime) function minus_date_time (self, other)
logical function eq (self, other)
logical function lt (self, other)
logical function gt (self, other)
logical function le (self, other)
logical function ge (self, other)
logical function ne (self, other)
subroutine trimzeros (string)
NAME
trimzeros(3fp) - [M_strings:NUMERIC] Delete trailing zeros from numeric decimal string (LICENSE:PD)
SYNOPSIS
subroutine a2r (chars, valu, ierr)
NAME
string_to_value(3f) - [M_strings:NUMERIC] subroutine returns numeric value from string (LICENSE:PD)
subroutine a2i (chars, valu, ierr)
subroutine a2d (chars, valu, ierr, onerr)
logical function decodebase (string, basein, out_baseten)
NAME
Variables
integer, parameter, public realtime =kind(0.0d0)
real(kind=realtime), parameter, private secday =86400.0d0
real(kind=realtime), parameter, public dt_minute =60.0d0
real(kind=realtime), parameter, public dt_hour =3600.0d0
real(kind=realtime), parameter, public dt_day =86400.0d0
real(kind=realtime), parameter, public dt_week =dt_day*7.0d0
Function/Subroutine Documentation
a2d()
subroutine m_time::a2d (character(len=*), intent(in) chars, doubleprecision, intent(out) valu, integer, intent(out) ierr, class(*), intent(in), optional onerr) private
References decodebase(), stderr(), and substitute().
a2i()
subroutine m_time::a2i (character(len=*), intent(in) chars, integer, intent(out) valu, integer, intent(out) ierr) private
References a2d(), and stderr().
a2r()
subroutine m_time::a2r (character(len=*), intent(in) chars, real, intent(out) valu, integer, intent(out) ierr) private
NAME
string_to_value(3f) - [M_strings:NUMERIC] subroutine returns numeric value from string (LICENSE:PD)
SYNOPSIS
subroutine string_to_value(chars,valu,ierr)
 character(len=*),intent(in)              :: chars   ! input string
 integer|real|doubleprecision,intent(out) :: valu
 integer,intent(out)                      :: ierr
DESCRIPTION
returns a numeric value from a numeric character string.
works with any g-format input, including integer, real, and exponential. If the input string begins with "B", "Z", or "O" and otherwise represents a positive whole number it is assumed to be a binary, hexadecimal, or octal value. If the string contains commas they are removed. If the string is of the form NN:MMM... or NN::MMM then NN is assumed to be the base of the whole number.
if an error occurs in the READ, IOSTAT is returned in IERR and value is set to zero. if no error occurs, IERR=0.
OPTIONS
CHARS input string to read numeric value from
RETURNS
VALU numeric value returned. May be INTEGER, REAL, or DOUBLEPRECISION. IERR error flag (0 == no error)
EXAMPLE
Sample Program:
 program demo_string_to_value
 use M_strings, only: string_to_value
 character(len=80) :: string
    string=' -40.5e-2 '
    call string_to_value(string,value,ierr)
    write(*,*) 'value of string ['//trim(string)//'] is ',value
 end program demo_string_to_value
AUTHOR
John S. Urban
LICENSE
Public Domain
References a2d(), and stderr().
adjustc()
pure character(len=:) function, allocatable, private m_time::adjustc (character(len=*), intent(in) string, integer, intent(in), optional length) private
NAME
adjustc(3f) - [M_strings:WHITESPACE] center text (LICENSE:PD)
SYNOPSIS
pure function adjustc(string[,length])
character(len=*),intent(in) :: string integer,intent(in),optional :: length character(len=:),allocatable :: adjustc
DESCRIPTION
Centers input text in a string of the length specified. Returns a string of length LENGTH if LENGTH is present. Otherwise returns a string of the length of the input string.
OPTIONS
string input string to trim and center length line length to center text in, optional.
RETURNS
adjustc centered output string
EXAMPLES
Sample Program:
 program demo_adjustc
 use M_strings, only : adjustc
 !  using length of the input string
    write(*,'(a)')       '================================'
    write(*,'(a)')adjustc('centered string                 ')
    write(*,'(a)')adjustc('                 centered string')
    write(*,'(a)')adjustc('  centered string               ')
 !  using explicit output string length
    write(*,'(a)')repeat('=',50)
    write(*,'(a)')adjustc('this is a centered string',50)
    write(*,'(a)')repeat('=',50)
 end program demo_adjustc
Expected output:
 \================================
         centered string
         centered string
         centered string
 \==================================================
             this is a centered string
 \==================================================
AUTHOR
John S. Urban
LICENSE
Public Domain
Parameters
[in] string PROCEDURE adjustc(3f) DESCRIPTION center text using implicit or explicit length
VERSION 2.0, 20160711
AUTHOR John S. Urban
box_month()
subroutine, public m_time::box_month (integer, dimension(8), intent(in) dat, character(len=wklen), dimension(8) calen)
NAME
box_month(3f) - [M_time] create specified month in a character array (LICENSE:PD)
SYNOPSIS
subroutine box_month(dat,calen)
 integer,intent(in)    :: dat(8)
 character(len=21)     :: calen(8)
DESCRIPTION
box_month(3f) uses a year and month from a date array to populate a small character array with a calendar representing the month.
OPTIONS
dat "DAT" array (an integer array of the same format as the array returned by the intrinsic DATE_AND_TIME(3f)) describing the date to be used to specify what calendar month to produce.
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
calen returned character array holding a display of the specified month
EXAMPLE
Sample program:XXX
  program demo_box_month
  use M_time, only : box_month
  implicit none
  integer           :: dat(8)
  character(len=21) :: calendar(8)
     call date_and_time(values=dat)
     call box_month(dat,calendar)
     write(*,'(a)')calendar
  end program demo_box_month
results:
   >     July 2016
   >Mo Tu We Th Fr Sa Su
   >             1  2  3
   > 4  5  6  7  8  9 10
   >11 12 13 14 15 16 17
   >18 19 20 21 22 23 24
   >25 26 27 28 29 30 31
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References adjustc(), date_to_julian(), dow(), julian_to_date(), and v2mo().
compact()
character(len=len(str)) function, private m_time::compact (character(len=*), intent(in) str, character(len=*), intent(in), optional char) private
NAME
compact(3f) - [M_strings:WHITESPACE] converts contiguous whitespace to a single character (or nothing) (LICENSE:PD)
SYNOPSIS
function compact(STR,CHAR) result (OUTSTR)
 character(len=*),intent(in)          :: STR
 character(len=*),intent(in),optional :: CHAR
 character(len=len(str))              :: OUTSTR
DESCRIPTION
COMPACT(3f) converts multiple spaces, tabs and control characters (called "whitespace") to a single character or nothing. Leading whitespace is removed.
OPTIONS
STR input string to reduce or remove whitespace from CHAR By default the character that replaces adjacent whitespace is a space. If the optional CHAR parameter is supplied it will be used to replace the whitespace. If a null character is supplied for CHAR whitespace is removed.
RETURNS
OUTSTR string of same length as input string but with all contiguous whitespace reduced to a single space and leading whitespace removed
EXAMPLES
Sample Program:
 program demo_compact
 use M_strings, only : compact
 implicit none
 ! produces 'This is a test               '
 write(*,*)compact('  This     is      a     test  ')
 ! produces 'Thisisatest                  '
 write(*,*)compact('  This     is      a     test  ',char='')
 ! produces 'This:is:a:test               '
 write(*,*)compact('  This     is      a     test  ',char=':')
 ! note CHAR is used to replace the whitespace, but if CHAR is
 ! in the original string it is just copied
 write(*,*)compact('A  AA    A   AAAAA',char='A')
 ! produces (original A characters are left as-is) 'AAAAAAAAAAAA'
 ! not 'A'
 end program demo_compact
Expected output
 >This is a test
 >Thisisatest
 >This:is:a:test
 >AAAAAAAAAAAA
AUTHOR
John S. Urban
LICENSE
Public Domain
construct_from_dat()
type(date_time) function m_time::construct_from_dat (integer, dimension(:), intent(in) dat) private
References u2d().
construct_from_jed()
type(date_time) function m_time::construct_from_jed (real(kind=realtime), intent(in) jed) private
References construct_from_dat(), and j2d().
construct_from_uet()
type(date_time) function m_time::construct_from_uet (integer, intent(in) uet) private
References construct_from_dat(), and u2d().
d2j()
real(kind=realtime) function, public m_time::d2j (integer, dimension(8), intent(in), optional dat)
NAME
d2j(3f) - [M_time] given DAT date-time array returns Julian Date (LICENSE:PD)
SYNOPSIS
function d2j(dat) result (julian)
 integer,intent(in)  :: dat(8)
 real(kind=realtime) :: julian
DESCRIPTION
given DAT date-time array returns Julian Date
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f). If not present, use current time.
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
julian The Julian Date.
EXAMPLE
Sample program:
 program demo_d2j
 use M_time, only : d2j
 implicit none
 integer :: dat(8)
    call date_and_time(values=dat)
    write(*,'(" Today is:",*(i0:,":"))')dat
    write(*,*)'Julian Date is ',d2j(dat)
 end program demo_d2j
results:
 Today is:2016:7:19:-240:2:11:50:885
 Julian Date is    2457588.7582278359
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References date_to_julian().
d2o()
integer function, public m_time::d2o (integer, dimension(8), intent(in), optional dat)
NAME
d2o(3f) - [M_time] converts DAT date-time array to Ordinal day (LICENSE:PD)
SYNOPSIS
function d2o(dat) result (ordinal)
 integer,intent(in),optional :: dat(8)   ! date time array
 integer                     :: ordinal  ! the returned day of the year
DESCRIPTION
Given a date in the form of a "DAT" array return the Ordinal Day, (ie. "the day of the year").
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
ordinal The day of the year calculated for the given input date, where Jan 1st=1.
EXAMPLE
Sample program:
 program demo_d2o
 use M_time, only : d2o
 implicit none
 integer :: dat(8)
    call date_and_time(values=dat)
    write(*,'(" Today is:",*(i0:,":"))')dat
    write(*,*)'Day of year is:',d2o(dat)
    ! year, month, day, timezone, hour, minute, seconds, milliseconds
    dat=[2020,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
    dat=[2021,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
    dat=[2022,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
    dat=[2023,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
    dat=[2024,12,31,-240,12,0,0,0]
    write(*,*)dat(1),' Days in year is:',d2o(dat)
 end program demo_d2o
results:
 Today is:2016:7:19:-240:20:1:19:829
 Day of year is:         201
        2020  Days in year is:         366
        2021  Days in year is:         365
        2022  Days in year is:         365
        2023  Days in year is:         365
        2024  Days in year is:         366
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References date_to_unix(), secday, and stderr().
d2s()
character(len=:) function, allocatable m_time::d2s (doubleprecision, intent(in) dvalue, character(len=*), intent(in), optional fmt) private
NAME
v2s(3f) - [M_strings:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
SYNOPSIS
   function v2s(value) result(outstr)
    integer|real|doubleprecision|logical,intent(in ) :: value
    character(len=:),allocatable :: outstr
    character(len=*),optional,intent(in) :: fmt
DESCRIPTION
v2s(3f) returns a representation of a numeric value as a string when given a numeric value of type REAL, DOUBLEPRECISION, INTEGER or LOGICAL. It creates the strings using internal WRITE() statements. Trailing zeros are removed from non-zero values, and the string is left-justified.
OPTIONS
VALUE input value to be converted to a string FMT format can be explicitly given, but is limited to generating a string of eighty or less characters.
RETURNS
OUTSTR returned string representing input value,
EXAMPLE
Sample Program:
 program demo_v2s
 use M_strings, only: v2s
 write(*,*) 'The value of 3.0/4.0 is ['//v2s(3.0/4.0)//']'
 write(*,*) 'The value of 1234    is ['//v2s(1234)//']'
 write(*,*) 'The value of 0d0     is ['//v2s(0d0)//']'
 write(*,*) 'The value of .false. is ['//v2s(.false.)//']'
 write(*,*) 'The value of .true. is  ['//v2s(.true.)//']'
 end program demo_v2s
Expected output
 The value of 3.0/4.0 is [0.75]
 The value of 1234    is [1234]
 The value of 0d0     is [0]
 The value of .false. is [F]
 The value of .true. is  [T]
AUTHOR
John S. Urban
LICENSE
Public Domain
References value_to_string().
d2u()
real(kind=realtime) function, public m_time::d2u (integer, dimension(8), intent(in), optional dat)
NAME
d2u(3f) - [M_time] given DAT date-time array returns Unix Epoch Time (UET starts at 0000 on 1 Jan. 1970, UTC) (LICENSE:PD)
SYNOPSIS
function d2u(dat) result (unixtime)
   integer,intent(in),optional :: dat(8)
   real(kind=realtime)         :: unixtime
DESCRIPTION
Converts a DAT date-time array to a Unix Epoch Time value. Typically mathematical operations such as sums, sorting and comparison are performed with simple UET numeric values, and then they are converted back.
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f). If not present the current time is used
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC.
EXAMPLE
Sample program:
 program demo_d2u
 use M_time, only : d2u
 implicit none
 integer           :: dat(8)
    call date_and_time(values=dat)
    write(*,'(" Today is:",*(i0:,":"))')dat
    write(*,*)'Unix Epoch time is ',d2u(dat)
 end program demo_d2u
results:
 Today is:2016:7:19:-240:2:0:48:561
 Unix Epoch time is    1468908048.5610321
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References date_to_unix().
d2w()
subroutine, public m_time::d2w (integer, dimension(8), intent(in) dat, integer, intent(out) iso_year, integer, intent(out) iso_week, integer, intent(out) iso_weekday, character(len=10), intent(out) iso_name)
NAME
d2w(3f) - [M_time] calculate iso-8601 Week-numbering year date yyyy-Www-d given DAT date-time array (LICENSE:PD)
SYNOPSIS
subroutine d2w(dat,iso_year,iso_week,iso_weekday,iso_name)
 integer,intent(in)              :: dat(8)     ! input date array
 integer,intent(out)             :: iso_year, iso_week, iso_weekday
 character(len=10),intent(out)   :: iso_name
DESCRIPTION
Given a "DAT" array defining a date and time, return the ISO-8601 Week in two formats – as three integer values defining the ISO year, week of year and weekday; and as a string of the form "yyyy-Www-d".
OPTIONS
dat "DAT" array (an integer array of the same format as the array returned by the intrinsic DATE_AND_TIME(3f)) describing the date, which is the basic time description used by the other M_time(3fm) module procedures.
RETURNS
iso_year ISO-8601 year number for the given date iso_week ISO-8601 week number for the given date iso_weekday ISO-8601 weekday number for the given date iso_name ISO-8601 Week string for the data in the form "yyyy-Www-d".
EXAMPLE
Sample program:
 program demo_d2w
 use M_time, only : d2w
 implicit none
 integer           :: dat(8)     ! input date array
 integer           :: iso_year, iso_week, iso_weekday
 character(len=10) :: iso_name
    call date_and_time(values=dat)
    call d2w(dat,iso_year,iso_week,iso_weekday,iso_name)
    write(*,'("ISO-8601 Week:   ",a)')iso_name
    write(*,'(a,i0)')'ISO-8601 year    ',iso_year
    write(*,'(a,i0)')'ISO-8601 week    ',iso_week
    write(*,'(a,i0)')'ISO-8601 weekday ',iso_weekday
 end program demo_d2w
results:
 ISO-8601 Week:   2016-W29-1
 ISO-8601 year    2016
 ISO-8601 week    29
 ISO-8601 weekday 1
DEFINITION
The ISO-8601 date and time standard was issued by the International Organization for Standardization (ISO). It is used (mainly) in government and business for fiscal years, as well as in timekeeping. The system specifies a week year atop the Gregorian calendar by defining a notation for ordinal weeks of the year.
An ISO week-numbering year (also called ISO year informally) has 52 or 53 full weeks. That is 364 or 371 days instead of the usual 365 or 366 days. The extra week is referred to here as a leap week, although ISO-8601 does not use this term. Weeks start with Monday. The first week of a year is the week that contains the first Thursday of the year (and, hence, always contains 4 January). ISO week year numbering therefore slightly deviates from the Gregorian for some days close to January 1st.
CALCULATION
The ISO-8601 week number of any date can be calculated, given its ordinal date (i.e. position within the year) and its day of the week.
METHOD
Using ISO weekday numbers (running from 1 for Monday to 7 for Sunday), subtract the weekday from the ordinal date, then add 10. Divide the result by 7. Ignore the remainder; the quotient equals the week number. If the week number thus obtained equals 0, it means that the given date belongs to the preceding (week-based) year. If a week number of 53 is obtained, one must check that the date is not actually in week 1 of the following year.
These two statements are assumed true when correcting the dates around January 1st:
o The number of weeks in a given year is equal to the corresponding week number of 28 December. o January 4th is always in the first week.
ISO_NAME
Week date representations are in the format YYYYWww-D.
o [YYYY] indicates the ISO week-numbering year which is slightly different from the traditional Gregorian calendar year. o [Www] is the week number prefixed by the letter W, from W01 through W53. o [D] is the weekday number, from 1 through 7, beginning with Monday and ending with Sunday.
For example, the Gregorian date 31 December 2006 corresponds to the Sunday of the 52nd week of 2006, and is written
2006-W52-7 (extended form) or 2006W527 (compact form).
REFERENCE
From Wikipedia, the free encyclopedia 2015-12-19
AUTHOR
John S. Urban, 2015-12-19
LICENSE
Public Domain
References uncorrected_week_of_year().
date_to_julian()
subroutine, public m_time::date_to_julian (integer, dimension(8), intent(in) dat, real(kind=realtime), intent(out) julian, integer, intent(out) ierr)
NAME
date_to_julian(3f) - [M_time] converts DAT date-time array to Julian Date (LICENSE:PD)
SYNOPSIS
subroutine date_to_julian(dat,juliandate,ierr)
 integer,intent(in)               :: dat(8)
 real(kind=realtime),intent(out)  :: juliandate
 integer,intent(out)              :: ierr
DESCRIPTION
Converts a DAT date-time array to a Unix Epoch Time (UET) value. UET is the number of seconds since 00:00 on January 1st, 1970, UTC.
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
juliandate A Julian Ephemeris Date (JED) is the number of days since noon (not midnight) on January 1st, 4713 BC. ierr Error code. If 0 no error occurred.
EXAMPLE
Sample Program:
 program demo_date_to_julian
 use M_time, only : date_to_julian,realtime
 implicit none
 integer             :: dat(8)
 real(kind=realtime) :: juliandate
 integer             :: ierr
    ! generate DAT array
    call date_and_time(values=dat)
    ! show DAT array
    write(*,'(" Today is:",*(i0:,":"))')dat
    ! convert DAT to Julian Date
    call date_to_julian(dat,juliandate,ierr)
    write(*,*)'Julian Date is ',juliandate
    write(*,*)'ierr is ',ierr
 end program demo_date_to_julian
results:
 Today is:2016:7:19:-240:11:3:13:821
 Julian Date is    2457589.1272432986
 ierr is            0
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
Parameters
[in] dat AUTHOR: John S. Urban
VERSION: 1.0 2015-12-21
REFERENCE: From Wikipedia, the free encyclopedia 2015-12-19
date_to_unix()
subroutine, public m_time::date_to_unix (integer, dimension(8), intent(in) dat, real(kind=realtime), intent(out) unixtime, integer, intent(out) ierr)
NAME
date_to_unix(3f) - [M_time] converts DAT date-time array to Unix Epoch Time (LICENSE:PD)
SYNOPSIS
subroutine date_to_unix(dat,unixtime,ierr)
 integer,intent(in)               :: dat(8)
 real(kind=realtime),intent(out)  :: unixtime
 integer,intent(out)              :: ierr
DESCRIPTION
Converts a DAT date-time array to a UET (Unix Epoch Time).
OPTIONS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC. ierr Error code. If 0 no error occurred.
EXAMPLE
Sample program:
 program demo_date_to_unix
 use M_time, only : date_to_unix, realtime
 implicit none
 integer             :: dat(8)
 real(kind=realtime) :: unixtime
 integer             :: ierr
    call date_and_time(values=dat)
    write(*,'(" Today is:",*(i0:,":"))')dat
    call date_to_unix(dat,unixtime,ierr)
    write(*,*)'Unix Epoch time is ',unixtime
    write(*,*)'ierr is ',ierr
 end program demo_date_to_unix
results:
 Today is:2016:7:18:-240:23:44:20:434
 Unix Epoch time is    1468899860.4340105
 ierr is            0
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References date_to_julian(), and secday.
days2sec()
real(kind=realtime) function, public m_time::days2sec (character(len=*), intent(in) str)
NAME
days2sec(3f) - [M_time] convert string of form [[-]dd-]hh:mm:ss.nn to seconds (LICENSE:PD)
SYNOPSIS
function days2sec(str) result(time)
 character(len=*),intent(in)       :: str
 real(kind=realtime)               :: time
DESCRIPTION
Given a string representing a duration of the form "[-][[[dd-]hh:]mm:]ss" or NNdNNhNNmNNsNNw return a value representing seconds
If "dd-" is present, units for the numbers are assumed to proceed from day to hour to minute to second. But if no day is present, the units are assumed to proceed from second to minutes to hour from left to right. That is ...
  [-]dd-hh:mm:ss
  [-]dd-hh:mm
  [-]dd-hh
  hh:mm:ss
  mm:ss
  ss
   Where dd is days, hh hours, mm minutes and ss seconds.
   A decimal fraction is supported on the seconds (Actually,
   any of the numeric values may represent positive floating
   point numbers). Spaces are ignored.
 NNdNNhNNmNNs
   Simple numeric values may also be used with unit suffixes; where
   s,m,h, or d represents seconds, minutes, hours or days and w
   represents a week. Allowed aliases for w,d,h,m, and s units are
                    d -  days,day
                    m -  minutes,minute,min,mins
                    h -  hours,hour,hr,hrs
                    s -  seconds,second,sec,secs
                    w -  week, weeks, wk, wks
   The numeric values may represent floating point numbers.
   Spaces, commas and case are ignored.
OPTIONS
str string of the general form dd-hh:mm:ss.nn
RETURNS
time the number of seconds represented by the input string
EXAMPLE
Sample program:
 program demo_days2sec
 use M_time, only : days2sec
 implicit none
    write(*,*)days2sec('1-12:04:20')
    write(*,*)'one second ',days2sec('1')
    write(*,*)'one minute ',days2sec('1:00')
    write(*,*)'one hour ',days2sec('1:00:00')
    write(*,*)'one day ',days2sec('1-00:00:00')
    write(*,*)nint(days2sec(' 1-12:04:20              ')) .eq. 129860
    write(*,*)nint(days2sec(' 1.5 days                ')) .eq. 129600
    write(*,*)nint(days2sec(' 1.5 days 4hrs 30minutes ')) .eq. 145800
    write(*,*)nint(days2sec(' 1.5d                    ')) .eq. 129600
    write(*,*)nint(days2sec(' 1d2h3m4s                ')) .eq. 93784
    ! duplicates
    write(*,*)nint(days2sec(' 1d1d1d                  ')) .eq. 259200
    ! negative values
    write(*,*)nint(days2sec(' 4d-12h                  ')) .eq. 302400
 end program demo_days2sec
Results:
 129860.00000000000
 one second    1.0000000000000000
 one minute    60.000000000000000
 one hour    3600.0000000000000
 one day    86400.000000000000
 T
 T
 T
 T
 T
 T
 T
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References compact(), lower(), s2v(), split(), substitute(), and transliterate().
decodebase()
logical function m_time::decodebase (character(len=*), intent(in) string, integer, intent(in) basein, integer, intent(out) out_baseten) private
NAME
decodebase(3f) - [M_strings:BASE] convert whole number string in base [2-36] to base 10 number (LICENSE:PD)
SYNOPSIS
logical function decodebase(string,basein,out10)
 character(len=*),intent(in)  :: string
 integer,intent(in)           :: basein
 integer,intent(out)          :: out10
DESCRIPTION
Convert a numeric string representing a whole number in base BASEIN to base 10. The function returns FALSE if BASEIN is not in the range [2..36] or if string STRING contains invalid characters in base BASEIN or if result OUT10 is too big
The letters A,B,...,Z represent 10,11,...,36 in the base > 10.
OPTIONS
string input string. It represents a whole number in the base specified by BASEIN unless BASEIN is set to zero. When BASEIN is zero STRING is assumed to be of the form BASE::VALUE where BASE represents the function normally provided by BASEIN. basein base of input string; either 0 or from 2 to 36. out10 output value in base 10
EXAMPLE
Sample program:
 program demo_decodebase
 use M_strings, only : codebase, decodebase
 implicit none
 integer           :: ba,bd
 character(len=40) :: x,y
 integer           :: r
 print *,' BASE CONVERSION'
 write(*,'("Start   Base (2 to 36): ")',advance='no'); read *, bd
 write(*,'("Arrival Base (2 to 36): ")',advance='no'); read *, ba
 INFINITE: do
    print *,''
    write(*,'("Enter number in start base: ")',advance='no'); read *, x
    if(x.eq.'0') exit INFINITE
    if(decodebase(x,bd,r)) then
       if(codebase(r,ba,y)) then
         write(*,'("In base ",I2,": ",A20)')  ba, y
       else
         print *,'Error in coding number.'
       endif
    else
       print *,'Error in decoding number.'
    endif
 enddo INFINITE
 end program demo_decodebase
AUTHOR
John S. Urban
Ref.: "Math matiques en Turbo-Pascal by M. Ducamp and A. Reverchon (2), Eyrolles, Paris, 1988".
based on a F90 Version By J-P Moreau (www.jpmoreau.fr)
LICENSE
Public Domain
References upper().
delta()
type(date_time) function, private m_time::delta (class(date_time), intent(in) self, integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional tz, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, integer, intent(in), optional week, character(len=*), intent(in), optional duration) private
References construct_from_dat(), d2u(), days2sec(), dt2d(), and u2d().
dow()
subroutine, public m_time::dow (integer, dimension(8), intent(in) values, integer, intent(out), optional weekday, character(len=*), intent(out), optional day, integer, intent(out), optional ierr)
NAME
dow(3f) - [M_time] given a date-time array DAT return the day of the week (LICENSE:PD)
SYNOPSIS
subroutine dow(values, weekday, day, ierr)
 integer,intent(in) :: values(8)
 integer,intent(out),optional :: weekday
 character(len=*),intent(out),optional :: day
 integer,intent(out),optional :: ierr
DESCRIPTION
Given a date array DAT return the day of the week as a number and a name, Mon=1.
OPTIONS
values "DAT" array (an integer array of the same format as the array returned by the intrinsic DATE_AND_TIME(3f)) describing the date to be used to calculate the day of the week.
RETURNS
weekday The numeric day of the week, starting with Monday=1. Optional. day The name of the day of the week. Optional. ierr Error code
     o [ 0] correct
     o [-1] invalid input date
     o [-2] neither day nor weekday return values were
            requested.
     If the error code is not returned and an error occurs,
     the program is stopped.
EXAMPLE
Sample program:
 program demo_dow
 use M_time, only : dow
 implicit none
 integer          :: dat(8)     ! input date array
 integer          :: weekday
 character(len=9) :: day
 integer          :: ierr
   call date_and_time(values=dat)
   call dow(dat, weekday, day, ierr)
   write(*,'(a,i0)')'weekday=',weekday
   write(*,'(a,a)')'day=',trim(day)
   write(*,'(a,i0)')'ierr=',ierr
 end program demo_dow
results:
 weekday=1
 day=Monday
 ierr=0
AUTHOR
John S. Urban, 2015-12-19
LICENSE
Public Domain
References date_to_julian().
dt2d()
integer function, dimension(8), private m_time::dt2d (class(date_time), intent(in) self) private
easter()
subroutine, public m_time::easter (integer, intent(in) year, integer, dimension(8), intent(out) dat)
NAME
easter(3f) - [M_time] calculate date for Easter given a year (LICENSE:PD)
SYNOPSIS
subroutine easter(year,dat)
integer, intent(in) :: year integer, intent(out) :: dat
DESCRIPTION
The Date of Easter (Sunday)
The algorithm is due to J.-M. Oudin (1940) and is reprinted in the Explanatory Supplement to the Astronomical Almanac, ed. P. K. Seidelmann (1992). See Chapter 12, "Calendars", by L. E. Doggett.
The following are dates of Easter from 1980 to 2024:
1980  April  6        1995  April 16        2010  April  4
1981  April 19        1996  April  7        2011  April 24
1982  April 11        1997  March 30        2012  April  8
1983  April  3        1998  April 12        2013  March 31
1984  April 22        1999  April  4        2014  April 20
1985  April  7        2000  April 23        2015  April  5
1986  March 30        2001  April 15        2016  March 27
1987  April 19        2002  March 31        2017  April 16
1988  April  3        2003  April 20        2018  April  1
1989  March 26        2004  April 11        2019  April 21
1990  April 15        2005  March 27        2020  April 12
1991  March 31        2006  April 16        2021  April  4
1992  April 19        2007  April  8        2022  April 17
1993  April 11        2008  March 23        2023  April  9
1994  April  3        2009  April 12        2024  March 31
 N.B. The date of Easter for the Eastern Orthodox Church may be different.
OPTIONS
year Year for which to calculate day that Easter falls on
RESULTS
dat Date array for noon on Easter for the specified year
EXAMPLE
Sample program:
 program demo_easter
 use M_time, only : easter, fmtdate
 implicit none
 integer :: year
 integer :: dat(8) ! year,month,day,tz,hour,minute,second,millisecond
   call date_and_time(values=dat)  ! get current year
   year=dat(1)
   call easter(year, dat)
   write(*,*)fmtdate(dat,&
   "Easter day: the %d day of %L in the year of our Lord %Y")
 end program demo_easter
Sample output:
 Easter day: the 16th day of April in the year of our Lord 2017
U.S. Naval Observatory Astronomical Applications Department
This code assembled by Alan Miller Reference web site: http://aa.usno.navy.mil/faq/docs/easter.html Latest revision 8 April 2002
epoch()
real(kind=realtime) function, private m_time::epoch (class(date_time), intent(in) self) private
References d2u(), and dt2d().
eq()
logical function m_time::eq (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u(), and dt2d().
fmtdate()
character(len=:) function, allocatable, public m_time::fmtdate (integer, dimension(8), intent(in) values, character(len=*), intent(in), optional format)
NAME
fmtdate(3f) - [M_time] given DAT date-time array return date as string using specified format (LICENSE:PD)
SYNOPSIS
function fmtdate(values,format) RESULT (timestr)
 integer,dimension(8),intent(in)      :: values
 character(len=*),intent(in),optional :: format
 character(len=:),allocatable         :: timestr
DESCRIPTION
The fmtdate(3f) procedure lets you reformat a DAT array in many common formats using a special string containing macro names beginning with ''. To see the allowable macros call or see the fmtdate_usage(3f) routine.
OPTIONS
values date in a "DAT" array, which is the same format as the values returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
format string describing how to format the "DAT" array. For a complete description of the formatting macros supported see fmtdate_usage(3f).
RETURNS
timestr formatted output string representing date
EXAMPLE
Sample program:
 program demo_fmtdate
 use M_time, only : fmtdate
 implicit none
 integer :: dat(8)
    call date_and_time(values=dat)
    write(*,*)fmtdate(dat,"current date: %w, %l %d, %Y %H:%m:%s %N")
    call showme()
 contains
 subroutine showme()
    use M_time, only : fmtdate_usage
    call fmtdate_usage() ! see all formatting options
 end subroutine showme
 end program demo_fmtdate
results:
   The current date is Sun, Jul 17th, 2016 01:21:35 PM
    ::
    :: An up-to-date description of all the
    :: formatting options will appear here
    ::
AUTHOR
John S. Urban, 2015-12-19
LICENSE
Public Domain
References d2o(), d2w(), date_to_julian(), date_to_unix(), dow(), easter(), format(), moon_fullness(), phase_of_moon(), substitute(), and v2mo().
fmtdate_usage()
subroutine, public m_time::fmtdate_usage (integer, intent(in), optional indent)
NAME
fmtdate_usage(3f) - [M_time] display macros recognized by fmtdate(3f) and now(3f) (LICENSE:PD)
SYNOPSIS
subroutine fmtdate_usage(indent)
 integer,intent(in),optional      :: indent
DESCRIPTION
The fmtdate_usage(3f) subroutine displays the formatting options available for use in procedures such as fmtdate(3f) and now(3f). It is typically used to produce up-to-date help text in commands that use the M_time(3fm) module, so that the formatting information only needs maintained in one place (this routine) and is easily displayed so users can quickly obtain a description of the formatting macros.
OPTIONS
indent how many spaces to prefix the output with, so that calling programs can position the output. Default for this optional parameter is three (3).
EXAMPLE
Sample Program:
 program demo_fmtdate_usage
 use M_time, only : fmtdate_usage
 implicit none
    call fmtdate_usage() ! see all formatting options
 end program demo_fmtdate_usage
results (actually call the routine to ensure this is up to date):
 Description                                        Example
 Base time array:
 (1) %Y -- year, yyyy                                2016
 (2) %M -- month of year, 01 to 12                   07
 (3) %D -- day of month, 01 to 31                    29
     %d -- day of month, with suffix (1st, 2nd,...)  29th
 (4) %Z -- minutes from UTC                          -0240
     %z -- -+hh:mm from UTC                          -04:00
     %T -- -+hhmm  from UTC                          -0400
 (5) %h -- hours, 00 to 23                           10
     %H -- hour (1 to 12, or twelve-hour clock)      10
     %N -- midnight< AM <=noon; noon<= PM <midnight  AM
 (6) %m -- minutes, 00 to 59                         54
 (7) %s -- sec, 00 to 59                             08
 (8) %x -- milliseconds 000 to 999                   521
 Conversions:
     %E -- Unix Epoch time                           1469804048.5220029
     %e -- integer value of Unix Epoch time          1469804049
     %J -- Julian  date                              2457599.121
     %j -- integer value of Julian Date(Julian Day)  2457599
     %O -- Ordinal day (day of year)                 211
     %o -- Whole days since Unix Epoch date          17011
     %U -- day of week, 1..7 Sunday=1                6
     %u -- day of week, 1..7 Monday=1                5
     %i -- ISO week of year 1..53                    30
     %I -- iso-8601 week-numbering date(yyyy-Www-d)  2016-W30-5
  Names:
     %l -- abbreviated month name                    Jul
     %L -- full month name                           July
     %w -- first three characters of weekday         Fri
     %W -- weekday name                              Friday
     %p -- phase of moon                             New
     %P -- percent of way from new to full moon      -1%
  Literals:
     %% -- a literal %                               %
     %t -- tab character
     %b -- blank character
     %B -- exclamation(bang) character
     %n -- new line (system dependent)
     %q -- single quote (apostrophe)
     %Q -- double quote
  Program timing:
     %c -- CPU_TIME(3f) output                       .21875000000000000
     %C -- number of times this routine is used      1
     %S -- seconds since last use of this format     .0000000000000000
     %k -- time in seconds from SYSTEM_CLOCK(3f)     723258.812
     %K -- time in clicks from SYSTEM_CLOCK(3f)      723258812
If no percent (%) is found in the format one of several
alternate substitutions occurs.
If the format is composed entirely of one of the following
keywords the following substitutions occur:
  "iso-8601",
  "iso"        ==> %Y-%M-%DT%h:%m:%s%z
  "iso-8601W",
  "isoweek"    ==> %I 2016-W30-5
  "sql"        ==> "%Y-%M-%D %h:%m:%s.%x"
  "sqlday"     ==> "%Y-%M-%D"
  "sqltime"    ==> "%h:%m:%s.%x"
  "rfc-2822"   ==> %w, %D %l %Y %h:%m:%s %T
  "rfc-3339"   ==> %Y-%M-%DT%h:%m:%s%z
  "date"       ==> %w %l %D %h:%m:%s UTC%z %Y
  "short"      ==> %w, %l %d, %Y %H:%m:%s %N UTC%z
  "long"," "   ==> %W, %L %d, %Y %H:%m:%s %N UTC%z
  "suffix"     ==> %Y%D%M%h%m%s
  "formal"     ==> The %d of %L %Y
  "lord"       ==> the %d day of %L in the year of our Lord %Y
  "easter"     ==> FOR THE YEAR OF THE CURRENT DATE:
                   Easter day: the %d day of %L in the year of our Lord %Y
  "all"        ==> A SAMPLE OF DATE FORMATS
otherwise the following words are replaced with the most
common macros:
   year     %Y  2016
   month    %M  07
   day      %D  29
   hour     %h  10
   minute   %m  54
   second   %s  08
   epoch    %e  1469804049
   julian   %j  2457599
   ordinal  %O  211
   weekday  %u  5
if none of these keywords are found then every letter that
is a macro is assumed to have an implied percent in front
of it. For example:
   YMDhms ==> %Y%M%D%h%m%s ==> 20160729105408
AUTHOR
John S. Urban, 2015-10-24
LICENSE
Public Domain
References now().
format()
character(len=:) function, allocatable, private m_time::format (class(date_time), intent(in) self, character(len=*), intent(in), optional fmt) private
References dt2d(), fmtdate(), and upper().
ge()
logical function m_time::ge (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u(), and dt2d().
get_timezone()
integer function m_time::get_timezone () private
gt()
logical function m_time::gt (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u(), and dt2d().
guessdate()
subroutine, public m_time::guessdate (character(len=*), intent(in) datestring, integer, dimension(8), intent(out) dat, integer, optional ier)
NAME
guessdate(3f) - [M_time] reads in a date, in various formats (LICENSE:PD)
SYNOPSIS
subroutine guessdate(anot,dat)
 character(len=*),intent(in) :: anot
 integer,intent(out)         :: dat(8)
DESCRIPTION
Read in strings and except for looking for month names remove non-numeric characters and try to convert a string assumed to represent a date to a date-time array.
Years should always be expressed as four-digit numbers, and except for the special format yyyy-mm-dd the day should come after the year. Named months are preferred. If ambiguous the order is assumed to be day - month - year. Times are assumed to be of the form HH:MM:SS
It is planned that this routine will be superseded. As an alternative, a C routine exists in the standard C libraries that allows for expansive features when reading dates that can be called via the ISO_C_BINDING interface.
OPTIONS
anot A string assumed to represent a date including a year, month and day.
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
EXAMPLE
Sample program:
 program demo_guessdate
 use M_time, only : guessdate, fmtdate
 implicit none
 character(len=20),allocatable :: datestrings(:)
 character(len=:),allocatable  :: answer
 integer                       :: dat(8)
 integer                       :: i
    datestrings=[ &
    & 'January 9th, 2001   ',&
    & ' Tue Jul 19 2016    ',&
    & ' 21/12/2016         ',&
    & ' 4th of Jul 2004    ' ]
    do i=1,size(datestrings)
       write(*,'(a)')repeat('-',80)
       write(*,*)'TRYING ',datestrings(i)
       call guessdate(datestrings(i),dat)
       write(*,*)'DAT ARRAY ',dat
       answer=fmtdate(dat)
       write(*,*)'FOR '//datestrings(i)//' GOT '//trim(answer)
    enddo
 end program demo_guessdate
results:
 ---------------------------------------------------------------------
 TRYING January 9th, 2001
 DAT ARRAY         2001  1  9   -240    0   0   0    0
 FOR January 9th, 2001    GOT Tuesday, January 9th, 2001 12:00:00 AM
 ---------------------------------------------------------------------
 TRYING  Tue Jul 19 2016
 DAT ARRAY         2016  7  19  -240    0   0   0    0
 FOR  Tue Jul 19 2016     GOT Tuesday, July 19th, 2016 12:00:00 AM
 ---------------------------------------------------------------------
 TRYING  21/12/2016
 DAT ARRAY         2016  12 21  -240    0   0   0    0
 FOR  21/12/2016          GOT Wednesday, December 21st, 2016 12:00:00 AM
 ---------------------------------------------------------------------
 TRYING  4th of Jul 2004
 DAT ARRAY         2004  7  4   -240    0   0   0    0
 FOR  4th of Jul 2004     GOT Sunday, July 4th, 2004 12:00:00 AM
LICENSE
Public Domain
References s2v(), split(), string_to_values(), substitute(), and upper().
i2s()
character(len=:) function, allocatable m_time::i2s (integer, intent(in) ivalue, character(len=*), intent(in), optional fmt) private
References value_to_string().
init_dt()
subroutine, private m_time::init_dt (class(date_time) self, integer, intent(in), optional year, integer, intent(in), optional month, integer, intent(in), optional day, integer, intent(in), optional tz, integer, intent(in), optional hour, integer, intent(in), optional minute, integer, intent(in), optional second, integer, intent(in), optional millisecond, character(len=*), intent(in), optional type, integer, dimension(8), intent(in), optional dat) private
References construct_from_dat(), d2u(), dt2d(), and u2d().
j2d()
integer function, dimension(8), public m_time::j2d (real(kind=realtime), intent(in) julian)
NAME
j2d(3f) - [M_time] given a JED (Julian Ephemeris Date) returns a date-time array DAT. (LICENSE:PD)
SYNOPSIS
function j2d(julian) result (dat)
 real(kind=realtime),intent(in),optional :: julian
 integer                                 :: dat(8)
DESCRIPTION
Converts a Julian Ephemeris Date to a DAT date-time array.
OPTIONS
julian A Julian Ephemeris Date (JED) is the number of days since noon (not midnight) on January 1st, 4713 BC. If not present, use current time.
RETURNS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
EXAMPLE
Sample program:
 program demo_j2d
 use M_time, only : j2d, d2j, fmtdate, realtime
 implicit none
 real(kind=realtime) :: today
 integer :: dat(8)
    call date_and_time(values=dat) ! get the date using intrinsic
    today=d2j(dat)                  ! convert today to Julian Date
    write(*,*)'Today=',fmtdate(j2d(today))
    ! math is easy with Julian Days and Julian Dates
    write(*,*)'Yesterday=',fmtdate(j2d(today-1.0d0))
    write(*,*)'Tomorrow=',fmtdate(j2d(today+1.0d0))
 end program demo_j2d
results:
 Today=Tuesday, July 19th, 2016 08:48:20 AM
 Yesterday=Monday, July 18th, 2016 08:48:20 AM
 Tomorrow=Wednesday, July 20th, 2016 08:48:20 AM
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References julian_to_date().
julian_oop()
real(kind=realtime) function, private m_time::julian_oop (class(date_time), intent(in) self) private
References d2j(), and dt2d().
julian_to_date()
subroutine, public m_time::julian_to_date (real(kind=realtime), intent(in) julian, integer, dimension(8), intent(out) dat, integer, intent(out) ierr)
NAME
julian_to_date(3f) - [M_time] converts a JED(Julian Ephemeris Date) to a DAT date-time array. (LICENSE:PD)
SYNOPSIS
subroutine julian_to_date(julian,dat,ierr)
 real(kind=realtime),intent(in) :: julian
 integer,intent(out)            :: dat(8)
 integer,intent(out)            :: ierr
DESCRIPTION
Converts a Unix Epoch Time (UET) value to a DAT date-time array. UET is the number of seconds since 00:00 on January 1st, 1970, UTC.
OPTIONS
julian Julian Date (days) dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f). ier 0 for successful execution
      dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
RETURNS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC. ierr Error code. If 0 no error occurred.
EXAMPLE
Sample program:
 program demo_julian_to_date
 use M_time, only : julian_to_date, fmtdate, realtime
 implicit none
 real(kind=realtime)     :: juliandate
 integer                 :: dat(8)
 integer                 :: ierr
    ! set sample Julian Date
    juliandate=2457589.129d0
    ! create DAT array for this date
    call julian_to_date(juliandate,dat,ierr)
    write(*,*)'Sample Date=',fmtdate(dat)
    ! go back one day
    call julian_to_date(juliandate-1.0d0,dat,ierr)
    write(*,*)'Day Before =',fmtdate(dat)
    ! go forward one day
    call julian_to_date(juliandate+1.0d0,dat,ierr)
    write(*,*)'Day After  =',fmtdate(dat)
 end program demo_julian_to_date
results:
 Sample Date=Tuesday, July 19th, 2016 11:05:45 AM UTC-04:00
 Day Before =Monday, July 18th, 2016 11:05:45 AM UTC-04:00
 Day After  =Wednesday, July 20th, 2016 11:05:45 AM UTC-04:00
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References get_timezone(), and secday.
l2s()
character(len=:) function, allocatable m_time::l2s (logical, intent(in) lvalue, character(len=*), intent(in), optional fmt) private
References value_to_string().
le()
logical function m_time::le (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u(), and dt2d().
lower()
elemental pure character(len(str)) function, private m_time::lower (character(*), intent(in) str, integer, intent(in), optional begin, integer, intent(in), optional end) private
NAME
lower(3f) - [M_strings:CASE] changes a string to lowercase over specified range (LICENSE:PD)
SYNOPSIS
elemental pure function lower(str,begin,end) result (string)
 character(*), intent(in) :: str
 integer,optional         :: begin, end
 character(len(str))      :: string  ! output string
DESCRIPTION
lower(string) returns a copy of the input string with all characters converted to miniscule over the specified range, assuming ASCII character sets are being used. If no range is specified the entire string is converted to miniscule.
OPTIONS
str string to convert to miniscule begin optional starting position in "str" to begin converting to miniscule end optional ending position in "str" to stop converting to miniscule
RESULTS
lower copy of the input string with all characters converted to miniscule over optionally specified range.
TRIVIA
The terms "uppercase" and "lowercase" date back to the early days of the mechanical printing press. Individual metal alloy casts of each needed letter, or punctuation symbol, were meticulously added to a press block, by hand, before rolling out copies of a page. These metal casts were stored and organized in wooden cases. The more often needed miniscule letters were placed closer to hand, in the lower cases of the work bench. The less often needed, capitalized, majuscule letters, ended up in the harder to reach upper cases.
EXAMPLE
Sample program:
 program demo_lower
 use M_time, only: lower
 implicit none
 character(len=:),allocatable  :: s
    s=' ABCDEFG abcdefg '
    write(*,*) 'mixed-case input string is ....',s
    write(*,*) 'lower-case output string is ...',lower(s)
 end program demo_lower
Expected output
   mixed-case input string is .... ABCDEFG abcdefg
   lower-case output string is ... abcdefg abcdefg
AUTHOR
John S. Urban
LICENSE
Public Domain
lt()
logical function m_time::lt (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u(), and dt2d().
minus_date_time()
real(kind=realtime) function m_time::minus_date_time (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u(), and dt2d().
minus_seconds()
type(date_time) function m_time::minus_seconds (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds) private
References construct_from_dat(), d2u(), dt2d(), and u2d().
mo2d()
integer function, dimension(8), public m_time::mo2d (character(len=*), intent(in) month_name, integer, intent(in), optional year)
NAME
mo2d(3f) - [M_time] given month name return DAT date-time array for beginning of that month in specified year (LICENSE:PD)
SYNOPSIS
   function mo2d(month_name) result (dat)
    character(len=*),intent(in) :: month_name
    integer                     :: dat(8)
DESCRIPTION
Given a Common Calendar month name, return the date as a "DAT" array for the 1st day of the month. An optional year may be specified. The year defaults to the current year.
OPTIONS
month_name A string representing a Common Calendar month name. year Optional year. Defaults to current year
RETURNS
dat An integer array that has the same structure as the array returned by the Fortran intrinsic DATE_AND_TIME(3f).
EXAMPLE
Sample program:
 program demo_mo2d
 use M_time, only : mo2d
 implicit none
    write(*,'(*(i0:,":"))')mo2d('March')
 end program demo_mo2d
results:
   2016:3:1:-240:0:0:0:0
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References mo2v(), and stderr().
mo2v()
integer function, public m_time::mo2v (character(len=*), intent(in) month_name)
NAME
mo2v(3f) - [M_time] given month name return month number (1-12) of that month (LICENSE:PD)
SYNOPSIS
function mo2v(month_name) result(imonth)
  character(len=*),intent(in):: month_name ! month name
  integer                    :: imonth     ! month number
DESCRIPTION
Given a string representing the name or abbreviation of a Gregorian Calendar month return a number representing the position of the month in the calendar starting with 1 for January and ending with 12 for December.
OPTIONS
month_name name or abbreviation of month. Case is ignored Once enough characters are found to uniquely identify a month the rest of the name is ignored.
RETURNS
imonth month number returned. If the name is not recognized a -1 is returned.
EXAMPLE
Sample program:
 program demo_mo2v
 use M_time, only : mo2v
 implicit none
    write(*,*)mo2v("April")
    write(*,*)mo2v('Apr')
    ! NOTE: still matches September, as "SE" was enough
    write(*,*)mo2v('sexember')
    write(*,*)mo2v('unknown')  ! returns -1
 end program demo_mo2v
results:
   >  4
   >  4
   >  9
   > -1
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References upper().
moon_fullness()
integer function, public m_time::moon_fullness (integer, dimension(8), intent(in) datin)
NAME
moon_fullness(3f) - [M_time] return percentage of moon phase from new to full (LICENSE:PD)
SYNOPSIS
function moon_fullness(datin)
integer,intent(in) :: datin(8) integer :: moon_fullness
DESCRIPTION
This procedure is used to support the P field descriptor for the fmtdate(3f) routine.
The moon circles the earth every 29.530588853 days on average, so pick a starting point and count. A new moon occurred at January 6, 2000, 18:14 UTC. Then it is easy to count the number of days since the last new moon. This is an approximate calculation.
OPTIONS
dat DAT Date array describing input date
RESULTS
moon_fullness 0 is a new or dark moon, 100 is a full moon, + for waxing and - for waning.
EXAMPLES
Sample:
 program demo_moon_fullness
 use M_time, only : now
 use M_time, only : phase_of_moon
 use M_time, only : moon_fullness
 implicit none
 integer             :: dat(8)
    ! generate DAT array
    call date_and_time(values=dat)
    ! show DAT array
    write(*,'(" Today is:",*(i0:,":"))')dat
    ! the %p and %P fields are supported by fmtdate(3f)
    write(*,*)now('The phase of the moon is %p, with a fullness of %P')
    write(*,'(1x,*(a))',advance='no')'The phase of the moon is ',trim( phase_of_moon(dat)),','
    write(*,'(1x,a,i0,a)')'with a fullness of ', moon_fullness(dat),'%'
 end program demo_moon_fullness
Sample output:
 Today is:2018:11:3:-240:20:18:44:245
 The phase of the moon is Waning crescent, with a fullness of -30%
 The phase of the moon is Waning crescent, with a fullness of -30%
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References d2j().
ne()
logical function m_time::ne (class(date_time), intent(in) self, type(date_time), intent(in) other) private
References d2u(), and dt2d().
now()
character(len=:) function, allocatable, public m_time::now (character(len=*), intent(in), optional format)
NAME
now(3f) - [M_time] return string representing current time given format (LICENSE:PD)
SYNOPSIS
function now(format) RESULT (timestr)
 character(len=*),intent(in)     :: format  ! input format string
 character(len=:),allocatable    :: timestr ! formatted date
DESCRIPTION
The now(3f) function is a call to the fmtdate(3f) function using the current date and time. That is, it is a convenient way to print the current date and time.
OPTIONS
format string describing how to format the current date and time. For a complete description of the formatting macros supported see fmtdate_usage(3f).
RETURNS
timestr formatted output string representing date
EXAMPLE
Sample Program:
 program demo_now
 use M_time, only : now
 implicit none
    write(*,*)now("The current date is %w, %l %d, %Y %H:%m:%s %N")
    call showme()
 contains
 subroutine showme() ! see all formatting options
 use M_time, only : fmtdate_usage
    call fmtdate_usage() ! see all formatting options
 end subroutine showme
 end program demo_now
results:
   The current date is Sun, Jul 17th, 2016 01:21:35 PM
    ::
    :: description of all formatting options will appear here
    ::
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References fmtdate(), and format().
o2d()
integer function, dimension(8), public m_time::o2d (integer, intent(in) ordinal, integer, optional year)
NAME
o2d(3f) - [M_time] converts Ordinal day to DAT date-time array (LICENSE:PD)
SYNOPSIS
function o2d(ordinal,[year]) result (dat)
 integer,intent(in) :: ordinal  ! the day of the year
 integer,optional   :: year     ! year
 integer            :: dat(8)   ! date time array
DESCRIPTION
Given an Ordinal day of the year return a date in the form of a "DAT" array.
OPTIONS
ordinal The day of the year for the given year, where Jan 1st=1.
year An optional year for the ordinal day. If not present the current year is assumed.
RETURNS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f). The timezone value is from the current time on the current platform.
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
EXAMPLE
Sample program:
 program demo_o2d
 use M_time, only : o2d,fmtdate
 implicit none
 integer :: year
    do year=2004,2008
       write(*,*)'100th day of ',year,' is ',fmtdate(o2d(100,year))
    enddo
    write(*,*)'100th day of this year is ',fmtdate(o2d(100))
 end program demo_o2d
results:
 100th day of 2004 is Friday, April 9th, 2004 00:00:00 PM UTC-02:40
 100th day of 2005 is Sunday, April 10th, 2005 00:00:00 PM UTC-02:40
 100th day of 2006 is Monday, April 10th, 2006 00:00:00 PM UTC-02:40
 100th day of 2007 is Tuesday, April 10th, 2007 00:00:00 PM UTC-02:40
 100th day of 2008 is Wednesday, April 9th, 2008 00:00:00 PM UTC-02:40
 100th day of this year is Saturday, April 9th, 2016 00:00:00 PM UTC-02:40
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References date_to_unix(), get_timezone(), stderr(), and u2d().
ordinal_oop()
integer function, private m_time::ordinal_oop (class(date_time), intent(in) self) private
References d2o(), and dt2d().
ordinal_seconds()
integer function, public m_time::ordinal_seconds ()
NAME
ordinal_seconds(3f) - [M_time] seconds since beginning of year (LICENSE:PD)
SYNOPSIS
function ordinal_seconds()
integer :: ordinal_seconds
DESCRIPTION
Return number of seconds since beginning of current year.
Before using this routine consider the consequences if the application is running at the moment a new year begins.
 2 147 483 647 / 31 536 000 ==> 68.09625973490613901572 years
EXAMPLE
Sample program
 program demo_ordinal_seconds
 use M_time, only : ordinal_seconds
 implicit none
 character(len=1) :: paws
 integer          :: ios
 integer          :: istart, iend
 istart=ordinal_seconds()
 write(*,'(a)',advance='no')'now pause. Enter return to continue ...'
 read(*,'(a)',iostat=ios) paws
 iend=ordinal_seconds()
 write(*,*)'that took ',iend-istart,'seconds'
 write(*,*)istart,iend
 end program demo_ordinal_seconds
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References d2o().
ordinal_to_date()
subroutine, public m_time::ordinal_to_date (integer yyyy, integer ddd, integer, dimension(8) dat)
NAME
ordinal_to_date(3f) - [M_time] when given a valid year and day of the year returns the DAT array for the date (LICENSE:PD)
SYNOPSIS
subroutine ordinal_to_date(yyyy, ddd, dat)
integer, intent(in) :: yyyy integer, intent(in) :: ddd integer, intent(out) :: dat
DESCRIPTION
When given a valid year, YYYY, and day of the year, DDD, returns the date as a DAT date array
OPTIONS
yyyy known year ddd known ordinal day of the year
RETURNS
dat DAT array describing the date
EXAMPLE
Sample program:
 program demo_datesub
 use M_time, only : ordinal_to_date
 implicit none
 INTEGER            :: yyyy, ddd, mm, dd
 integer            :: dat(8)
 integer            :: ios
   INFINITE: do
      write(*,'(a)',advance='no')'Enter year YYYY and ordinal day of year DD '
      read(*,*,iostat=ios)yyyy,ddd
      if(ios.ne.0)exit INFINITE
      ! recover month and day from year and day number.
      call ordinal_to_date(yyyy, ddd, dat)
      mm=dat(2)
      dd=dat(3)
    enddo INFINITE
 end program demo_datesub
References d2j(), and j2d().
phase_of_moon()
character(len=:) function, allocatable, public m_time::phase_of_moon (integer, dimension(8), intent(in) datin)
NAME
phase_of_moon(3f) - [M_time] return name for phase of moon for given date (LICENSE:PD)
SYNOPSIS
function phase_of_moon(datin)
integer,intent(in) :: datin(8) character(len=:),allocatable :: phase_of_moon
DESCRIPTION
Phases Of The Moon
This procedure is used to support the p field descriptor for the fmtdate(3f) routine.
The moon circles the earth every 29.530588853 days on average, so pick a starting point and count. A new moon occurred at Julian date 2451550.1 (January 6, 2000, 18:14 UTC). Then it is easy to count the number of days since the last new moon. This is an approximate calculation.
There are eight generally recognized phases of the moon in common use
o new or dark o waxing crescent o first quarter o waxing gibbous o full o waning gibbous o laster quarter o waning crescent
To calculate the phase of the moon simply divide the days since the last new moon by eight and select the appropriate phase.
Note that technically the four states (new, first quarter, full, third quarter) are events not phases. That is to say, the moon is technically only new for an instant.
EXAMPLES
Sample:
 program demo_phase_of_moon
 use M_time, only : now
 use M_time, only : phase_of_moon
 use M_time, only : moon_fullness
 implicit none
 integer             :: dat(8)
    ! generate DAT array
    call date_and_time(values=dat)
    ! show DAT array
    write(*,'(" Today is:",*(i0:,":"))')dat
    ! the %p and %P fields are supported by fmtdate(3f)
    write(*,*)now('The phase of the moon is %p, with a fullness of %P')
    write(*,'(1x,*(a))',advance='no')'The phase of the moon is ',trim( phase_of_moon(dat)),','
    write(*,'(1x,a,i0,a)')'with a fullness of ', moon_fullness(dat),'%'
 end program demo_phase_of_moon
Sample output:
 Today is:2018:11:3:-240:20:18:44:245
 The phase of the moon is Waning crescent, with a fullness of -30%
 The phase of the moon is Waning crescent, with a fullness of -30%
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References d2j().
plus_seconds()
type(date_time) function m_time::plus_seconds (class(date_time), intent(in) self, real(kind=realtime), intent(in) seconds) private
References construct_from_dat(), d2u(), dt2d(), and u2d().
r2s()
character(len=:) function, allocatable m_time::r2s (real, intent(in) rvalue, character(len=*), intent(in), optional fmt) private
References value_to_string().
s2v()
doubleprecision function, private m_time::s2v (character(len=*), intent(in) chars, integer, optional ierr, class(*), intent(in), optional onerr) private
NAME
s2v(3f) - [M_strings:NUMERIC] function returns doubleprecision numeric value from a string (LICENSE:PD)
SYNOPSIS
function s2v(string[,ierr][,onerr])
 character(len=*)             :: string
 doubleprecision              :: s2v
 integer,intent(out),optional :: ierr
 class(*),intent(in),optional :: onerr
DESCRIPTION
This function converts a string to a DOUBLEPRECISION numeric value.
The intrinsics INT(3f), REAL(3f), and DBLE(3f) are also extended to take CHARACTER variables. The KIND= keyword is not supported on the extensions.
OPTIONS
 string   holds string assumed to represent a numeric value
 ierr     If an error occurs the program is stopped if the optional
          parameter IERR is not present. If IERR returns a non-zero
          value an error occurred.
 onerr    The value to return on error. A value of zero (NaN) is
          returned on error by default.
RETURNS
s2v
EXAMPLE
Sample Program:
 program demo_s2v
 use M_strings, only: s2v, int, real, dble
 implicit none
 character(len=8)              :: s=' 10.345 '
 integer                       :: i
 character(len=14),allocatable :: strings(:)
 doubleprecision               :: dv
 integer                       :: errnum
 ! different strings representing INTEGER, REAL, and DOUBLEPRECISION
 strings=[&
 &' 10.345       ',&
 &'+10           ',&
 &'    -3        ',&
 &'    -4.94e-2  ',&
 &'0.1           ',&
 &'12345.678910d0',&
 &'              ',& ! Note: will return zero without an error message
 &'1 2 1 2 1 . 0 ',& ! Note: spaces will be ignored
 &'WHAT?         ']  ! Note: error messages will appear, zero returned
 ! a numeric value is returned, so it can be used in numeric expression
 write(*,*) '1/2 value of string is ',s2v(s)/2.0d0
 write(*,*)
 write(*,*)' STRING            VALUE                    ERROR_NUMBER'
 do i=1,size(strings)
    ! Note: not a good idea to use s2v(3f) in a WRITE(3f) statement,
    ! as it does I/O when errors occur, so called on a separate line
    dv=s2v(strings(i),errnum)
    write(*,*) strings(i)//'=',dv,errnum
 enddo
 write(*,*)"Extended intrinsics"
 write(*,*)'given inputs:',s,strings(:8)
 write(*,*)'INT(3f):',int(s),int(strings(:8))
 write(*,*)'REAL(3f):',real(s),real(strings(:8))
 write(*,*)'DBLE(3f):',dble(s),dble(strings(:8))
 write(*,*)"That's all folks!"
 end program demo_s2v
Expected output
 >1/2 value of string is    5.1725000000000003
 >
 > STRING            VALUE                    ERROR_NUMBER
 > 10.345       =   10.345000000000001                0
 >+10           =   10.000000000000000                0
 >    -3        =  -3.0000000000000000                0
 >    -4.94e-2  =  -4.9399999999999999E-002           0
 >0.1           =  0.10000000000000001                0
 >12345.678910d0=   12345.678910000001                0
 >              =   0.0000000000000000                0
 >1 2 1 2 1 . 0 =   12121.000000000000                0
 >*a2d* - cannot produce number from string [WHAT?]
 >*a2d* - [Bad value during floating point read]
 >WHAT?         =   0.0000000000000000             5010
 >Extended intrinsics
 >given inputs: 10.345 10.345 +10 -3 -4.94e-2 0.1 12345.678910d0 1 2 1 2 1 . 0
 >INT(3f): 10 10 10 -3 0 0 12345 0 12121
 >REAL(3f): 10.3450003 10.3450003 10.0000000 -3.00000000 -4.94000018E-02
 >          0.100000001 12345.6787 0.00000000 12121.0000
 >DBLE(3f): 10.345000000000001 10.345000000000001 10.000000000000000
 >          -3.0000000000000000 -4.9399999999999999E-002 0.10000000000000001
 >          12345.678910000001 0.0000000000000000 12121.000000000000
 >That's all folks!
AUTHOR
John S. Urban
LICENSE
Public Domain
PROCEDURE:
DESCRIPTION: s2v(3f): function returns doubleprecision number from string;zero if error occurs
VERSION: 2.0, 20160704
AUTHOR: John S. Urban
References a2d().
sec2days()
character(len=:) function, allocatable, public m_time::sec2days (class(*), intent(in) seconds, logical, intent(in), optional crop)
NAME
sec2days(3f) - [M_time] convert seconds to string of form dd-hh:mm:ss (LICENSE:PD)
SYNOPSIS
function sec2days(seconds,crop) result(dhms)
 real(kind=realtime),intent(in) :: seconds
   or
 integer,intent(in)             :: seconds
   or
 real,intent(in)                :: seconds
   or
 character(len=*)               :: seconds
 logical,intent(in),optional    :: crop
 character(len=:),allocatable   :: dhms
DESCRIPTION
Given a number of seconds convert it to a string of the form
dd-hh:mm:ss
where dd is days, hh hours, mm minutes and ss seconds.
OPTIONS
seconds number of seconds to convert to string of form dd-hh:mm:ss. May be of type INTEGER, REAL, REAL(KIND=REALTIME), or CHARACTER.
CHARACTER strings may be of the form NNdNNhNNmNNs. Case,spaces and underscores are ignored. Allowed aliases for d,h,m, and s units are
d -  days,day
m -  minutes,minute,min
h -  hours,hour,hrs,hr
s -  seconds,second,sec
The numeric values may represent floating point numbers.
crop if .true., remove leading zero day values or day and hour values. Optional, defaults to .false. .
RETURNS
dmhs the returned string of form [d:h:]m:s
EXAMPLE
Sample Program:
 program demo_sec2days
 use M_time, only : sec2days
 implicit none
    write(*,*)sec2days(129860)
    write(*,*)sec2days(80000.0d0)
    write(*,*)sec2days(80000.0,crop=.true.)
    write(*,*)sec2days('1 day 2.0hr 100 min 300.0seconds')
 end program demo_sec2days
results:
 1-12:04:20
 0-22:13:20
 22:13:20
 1-03:45:00
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References compact(), lower(), s2v(), split(), substitute(), and transliterate().
split()
subroutine, private m_time::split (character(len=*), intent(in) input_line, character(len=:), dimension(:), intent(out), allocatable array, character(len=*), intent(in), optional delimiters, character(len=*), intent(in), optional order, character(len=*), intent(in), optional nulls) private
NAME
split(3f) - [M_strings:TOKENS] parse string into an array using specified delimiters (LICENSE:PD)
SYNOPSIS
subroutine split(input_line,array,delimiters,order,nulls)
 character(len=*),intent(in)              :: input_line
 character(len=:),allocatable,intent(out) :: array(:)
 character(len=*),optional,intent(in)     :: delimiters
 character(len=*),optional,intent(in)     :: order
 character(len=*),optional,intent(in)     :: nulls
DESCRIPTION
SPLIT(3f) parses a string using specified delimiter characters and store tokens into an allocatable array
OPTIONS
INPUT_LINE  Input string to tokenize
ARRAY       Output array of tokens
DELIMITERS  List of delimiter characters.
            The default delimiters are the "whitespace" characters
            (space, tab,new line, vertical tab, formfeed, carriage
            return, and null). You may specify an alternate set of
            delimiter characters.
            Multi-character delimiters are not supported (Each
            character in the DELIMITERS list is considered to be
            a delimiter).
            Quoting of delimiter characters is not supported.
ORDER SEQUENTIAL|REVERSE|RIGHT  Order of output array.
            By default ARRAY contains the tokens having parsed
            the INPUT_LINE from left to right. If ORDER='RIGHT'
            or ORDER='REVERSE' the parsing goes from right to left.
NULLS IGNORE|RETURN|IGNOREEND  Treatment of null fields.
            By default adjacent delimiters in the input string
            do not create an empty string in the output array. if
            NULLS='return' adjacent delimiters create an empty element
            in the output ARRAY. If NULLS='ignoreend' then only
            trailing delimiters at the right of the string are ignored.
EXAMPLES
Sample program:
 program demo_split
 use M_strings, only: split
 character(len=*),parameter     :: &
 & line='  aBcdef   ghijklmnop qrstuvwxyz  1:|:2     333|333 a B cc    '
 character(len=:),allocatable :: array(:) ! output array of tokens
    write(*,*)'INPUT LINE:['//LINE//']'
    write(*,'(80("="))')
    write(*,*)'typical call:'
    CALL split(line,array)
    write(*,'(i0," ==> ",a)')(i,trim(array(i)),i=1,size(array))
    write(*,*)'SIZE:',SIZE(array)
    write(*,'(80("-"))')
    write(*,*)'custom list of delimiters (colon and vertical line):'
    CALL split(line,array,delimiters=':|',order='sequential',nulls='ignore')
    write(*,'(i0," ==> ",a)')(i,trim(array(i)),i=1,size(array))
    write(*,*)'SIZE:',SIZE(array)
    write(*,'(80("-"))')
    write(*,*)&
    &'custom list of delimiters, reverse array order and count null fields:'
    CALL split(line,array,delimiters=':|',order='reverse',nulls='return')
    write(*,'(i0," ==> ",a)')(i,trim(array(i)),i=1,size(array))
    write(*,*)'SIZE:',SIZE(array)
    write(*,'(80("-"))')
    write(*,*)'INPUT LINE:['//LINE//']'
    write(*,*)&
    &'default delimiters and reverse array order and return null fields:'
    CALL split(line,array,delimiters='',order='reverse',nulls='return')
    write(*,'(i0," ==> ",a)')(i,trim(array(i)),i=1,size(array))
    write(*,*)'SIZE:',SIZE(array)
end program demo_split
Output
 > INPUT LINE:[  aBcdef   ghijklmnop qrstuvwxyz  1:|:2     333|333 a B cc    ]
 > ===========================================================================
 >  typical call:
 > 1 ==> aBcdef
 > 2 ==> ghijklmnop
 > 3 ==> qrstuvwxyz
 > 4 ==> 1:|:2
 > 5 ==> 333|333
 > 6 ==> a
 > 7 ==> B
 > 8 ==> cc
 >  SIZE:           8
 > --------------------------------------------------------------------------
 >  custom list of delimiters (colon and vertical line):
 > 1 ==>   aBcdef   ghijklmnop qrstuvwxyz  1
 > 2 ==> 2     333
 > 3 ==> 333 a B cc
 >  SIZE:           3
 > --------------------------------------------------------------------------
 >  custom list of delimiters, reverse array order and return null fields:
 > 1 ==> 333 a B cc
 > 2 ==> 2     333
 > 3 ==>
 > 4 ==>
 > 5 ==>   aBcdef   ghijklmnop qrstuvwxyz  1
 >  SIZE:           5
 > --------------------------------------------------------------------------
 >  INPUT LINE:[  aBcdef   ghijklmnop qrstuvwxyz  1:|:2     333|333 a B cc    ]
 >  default delimiters and reverse array order and count null fields:
 > 1 ==>
 > 2 ==>
 > 3 ==>
 > 4 ==> cc
 > 5 ==> B
 > 6 ==> a
 > 7 ==> 333|333
 > 8 ==>
 > 9 ==>
 > 10 ==>
 > 11 ==>
 > 12 ==> 1:|:2
 > 13 ==>
 > 14 ==> qrstuvwxyz
 > 15 ==> ghijklmnop
 > 16 ==>
 > 17 ==>
 > 18 ==> aBcdef
 > 19 ==>
 > 20 ==>
 >  SIZE:          20
AUTHOR
John S. Urban
LICENSE
Public Domain
References lower().
stderr()
subroutine m_time::stderr (character(len=*) string) private
string_to_values()
subroutine, private m_time::string_to_values (character(len=*), intent(in) line, integer, intent(in) iread, real, dimension(iread), intent(inout) values, integer, intent(out) inums, character(len=*), intent(in) delims, integer, intent(out) ierr) private
NAME
string_to_values(3f) - [M_strings:NUMERIC] read a string representing numbers into a numeric array (LICENSE:PD)
SYNOPSIS
   subroutine string_to_values(line,iread,values,inums,delims,ierr)
    character(len=*) :: line
    integer          :: iread
    real             :: values(*)
    integer          :: inums
    character(len=*) :: delims
    integer          :: ierr
DESCRIPTION
This routine can take a string representing a series of numbers and convert it to a numeric array and return how many numbers were found.
OPTIONS
   LINE     Input string containing numbers
   IREAD    maximum number of values to try to read from input string
RESULTS
   VALUES   real array to be filled with numbers
   INUMS    number of values successfully read (before error occurs
            if one does)
   DELIMS   delimiter character(s), usually a space. must not be a
            null string. If more than one character, a space must
            not be the last character or it will be ignored.
   IERR     error flag (0=no error, else column number string starts
            at that error occurred on).
EXAMPLE
Sample Program:
 program demo_string_to_values
  use M_strings, only : string_to_values
  character(len=80)  :: s=' 10 20e3;3.45 -400.3e-2;1234; 5678 '
  integer,parameter  :: isz=10
  real               :: array(isz)
  call string_to_values(s,10,array,inums,' ;',ierr)
  call reportit()
  call string_to_values('10;2.3;3.1416',isz,array,inums,' ;',ierr)
  call reportit()
  contains
     subroutine reportit()
        write(*,*)'string_to_values:'
        write(*,*)'input string.............',trim(s)
        write(*,*)'number of values found...',inums
        write(*,*)'values...................',(array(ii),ii=1,inums)
     end subroutine reportit
 end program demo_string_to_values
Expected output
string_to_values:
input string............. 10 20e3;3.45 -400.3e-2;1234; 5678
number of values found...           6
values...................   10.0000000  20000.0000  3.45000005  -4.00299978  1234.00000  5678.00000
string_to_values:
input string............. 10 20e3;3.45 -400.3e-2;1234; 5678
number of values found...           3
values...................   10.0000000  2.29999995  3.14159989
AUTHOR
John S. Urban
LICENSE
Public Domain
References stderr().
substitute()
subroutine, private m_time::substitute (character(len=*) targetline, character(len=*), intent(in) old, character(len=*), intent(in) new, integer, intent(out), optional ierr, integer, intent(in), optional start, integer, intent(in), optional end) private
NAME
substitute(3f) - [M_strings:EDITING] subroutine globally substitutes one substring for another in string (LICENSE:PD)
SYNOPSIS
subroutine substitute(targetline,old,new,ierr,start,end)
 character(len=*)              :: targetline
 character(len=*),intent(in)   :: old
 character(len=*),intent(in)   :: new
 integer,intent(out),optional  :: ierr
 integer,intent(in),optional   :: start
 integer,intent(in),optional   :: end
DESCRIPTION
Globally substitute one substring for another in string.
OPTIONS
TARGETLINE input line to be changed. Must be long enough to hold altered output. OLD substring to find and replace NEW replacement for OLD substring IERR error code. If IER = -1 bad directive, >= 0 then count of changes made. START sets the left margin to be scanned for OLD in TARGETLINE. END sets the right margin to be scanned for OLD in TARGETLINE.
EXAMPLES
Sample Program:
 program demo_substitute
 use M_time, only : substitute
 implicit none
 ! must be long enough to hold changed line
 character(len=80) :: targetline
 targetline='this is the input string'
 write(*,*)'ORIGINAL    : '//trim(targetline)
 ! changes the input to 'THis is THe input string'
 call substitute(targetline,'th','TH')
 write(*,*)'th => TH    : '//trim(targetline)
 ! a null old substring means "at beginning of line"
 ! changes the input to 'BEFORE:this is the input string'
 call substitute(targetline,'','BEFORE:')
 write(*,*)'"" => BEFORE: '//trim(targetline)
 ! a null new string deletes occurrences of the old substring
 ! changes the input to 'ths s the nput strng'
 call substitute(targetline,'i','')
 write(*,*)'i => ""     : '//trim(targetline)
 end program demo_substitute
Expected output
 ORIGINAL    : this is the input string
 th => TH    : THis is THe input string
 "" => BEFORE: BEFORE:THis is THe input string
 i => ""     : BEFORE:THs s THe nput strng
AUTHOR
John S. Urban
LICENSE
Public Domain
References stderr().
transliterate()
pure character(len=len(instr)) function, private m_time::transliterate (character(len=*), intent(in) instr, character(len=*), intent(in) old_set, character(len=*), intent(in) new_set) private
NAME
transliterate(3f) - [M_strings:EDITING] replace characters from old set with new set (LICENSE:PD)
SYNOPSIS
pure function transliterate(instr,old_set,new_set) result(outstr)
 character(len=*),intent(in)  :: instr
 character(len=*),intent(in)  :: old_set
 character(len=*),intent(in)  :: new_set
 character(len=len(instr))    :: outstr
DESCRIPTION
Translate, squeeze, and/or delete characters from the input string.
OPTIONS
instr input string to change old_set list of letters to change in INSTR if found
     Each character in the input string that matches a character in
     the old set is replaced.
new_set list of letters to replace letters in OLD_SET with.
     If the new_set is the empty set the matched characters are deleted.
     If the new_set is shorter than the old set the last character in the
     new set is used to replace the remaining characters in the new set.
RETURNS
outstr instr with substitutions applied
EXAMPLES
Sample Program:
 program demo_transliterate
 use M_strings, only : transliterate
 implicit none
 character(len=80)   :: STRING
 STRING='aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ'
 write(*,'(a)') STRING
 ! convert a string to uppercase:
 write(*,*) TRANSLITERATE(STRING,'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ')
 ! change all miniscule letters to a colon (":"):
 write(*,*) TRANSLITERATE(STRING,'abcdefghijklmnopqrstuvwxyz',':')
 ! delete all miniscule letters
 write(*,*) TRANSLITERATE(STRING,'abcdefghijklmnopqrstuvwxyz','')
 end program demo_transliterate
Expected output
 > aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ
 > AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZ
 > :A:B:C:D:E:F:G:H:I:J:K:L:M:N:O:P:Q:R:S:T:U:V:W:X:Y:Z
 > ABCDEFGHIJKLMNOPQRSTUVWXYZ
AUTHOR
John S. Urban
LICENSE
Public Domain
trimzeros()
subroutine m_time::trimzeros (character(len=*) string) private
NAME
trimzeros(3fp) - [M_strings:NUMERIC] Delete trailing zeros from numeric decimal string (LICENSE:PD)
SYNOPSIS
subroutine trimzeros(str)
character(len=*) :: str
DESCRIPTION
TRIMZEROS(3f) deletes trailing zeros from a string representing a number. If the resulting string would end in a decimal point, one trailing zero is added.
OPTIONS
str input string will be assumed to be a numeric value and have trailing zeros removed
EXAMPLES
Sample program:
   program demo_trimzeros
   use M_strings, only : trimzeros
   character(len=:),allocatable :: string
      write(*,*)trimzeros('123.450000000000')
      write(*,*)trimzeros('12345')
      write(*,*)trimzeros('12345.')
      write(*,*)trimzeros('12345.00e3')
   end program demo_trimzeros
AUTHOR
John S. Urban
LICENSE
Public Domain
u2d()
integer function, dimension(8), public m_time::u2d (class(*), intent(in), optional unixtime)
NAME
u2d(3f) - [M_time] given Unix Epoch Time returns DAT date-time array (LICENSE:PD)
SYNOPSIS
function u2d(unixtime) result (dat)
 class(*),intent(in),optional      :: unixtime
 ! integer
 ! real
 ! real(kind=realtime)
 integer                           :: dat(8)
DESCRIPTION
Given Unix Epoch Time returns DAT date-time array
OPTIONS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC. If not present, use current time.
RETURNS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
EXAMPLE
Sample program:
 program demo_u2d
 use M_time, only : u2d, d2u, fmtdate, realtime
 implicit none
 real(kind=realtime) :: today
 integer :: dat(8)
    call date_and_time(values=dat) ! get the date using intrinsic
    today=d2u(dat)                 ! convert today to Julian Date
    write(*,*)'Today=',fmtdate(u2d(today))
    write(*,*)'Yesterday=',fmtdate(u2d(today-86400.0d0)) ! subtract day
    write(*,*)'Tomorrow=',fmtdate(u2d(today+86400.0d0))  ! add day
 end program demo_u2d
results:
 Today=Tuesday, July 19th, 2016 11:10:08 AM
 Yesterday=Monday, July 18th, 2016 11:10:08 AM
 Tomorrow=Wednesday, July 20th, 2016 11:10:08 AM
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References d2u(), and unix_to_date().
unix_to_date()
subroutine, public m_time::unix_to_date (class(*), intent(in) unixtime, integer, dimension(8), intent(out) dat, integer, intent(out) ierr)
NAME
unix_to_date(3f) - [M_time] converts Unix Epoch Time to DAT date-time array (LICENSE:PD)
SYNOPSIS
subroutine unix_to_date(unixtime,dat,ierr)
 real(kind=realtime),intent(in) :: unixtime ! Unix time (seconds)
 integer,intent(out)            :: dat(8)   ! date and time array
 integer,intent(out)            :: ierr     ! 0 for successful execution
DESCRIPTION
Converts a Unix Epoch Time (UET) to a DAT date-time array.
OPTIONS
unixtime The "Unix Epoch" time, or the number of seconds since 00:00:00 on January 1st, 1970, UTC; of type real(kind=realtime).
RETURNS
dat Integer array holding a "DAT" array, similar in structure to the array returned by the intrinsic DATE_AND_TIME(3f).
dat=[year,month,day,timezone,hour,minutes,seconds,milliseconds]
ierr Error code. If 0 no error occurred.
EXAMPLE
Sample program:
 program demo_unix_to_date
 use M_time, only : unix_to_date, u2d, fmtdate, realtime
 implicit none
 real(kind=realtime)           :: unixtime
 real(kind=realtime),parameter :: DAY=86400.0d0 ! seconds in a day
 integer                       :: dat(8)
 integer                       :: ierr
    unixtime=1468939038.4639933d0            ! sample Unix Epoch time
    call unix_to_date(unixtime,dat,ierr)     ! create DAT array for today
    write(*,*)'Sample Date=',fmtdate(dat)
    call unix_to_date(unixtime-DAY,dat,ierr) ! go back one day
    write(*,*)'Day Before =',fmtdate(dat)    ! subtract day and print
    call unix_to_date(unixtime+DAY,dat,ierr) ! go forward one day
    write(*,*)'Day After  =',fmtdate(dat)    ! add day print
 end program demo_unix_to_date
results:
 Sample Date=Tuesday, July 19th, 2016 10:37:18 AM
 Day Before =Monday, July 18th, 2016 10:37:18 AM
 Day After  =Wednesday, July 20th, 2016 10:37:18 AM
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References date_to_julian(), julian_to_date(), and secday.
upper()
elemental pure character(len(str)) function, private m_time::upper (character(*), intent(in) str, integer, intent(in), optional begin, integer, intent(in), optional end) private
NAME
upper(3f) - [M_strings:CASE] changes a string to uppercase (LICENSE:PD)
SYNOPSIS
elemental pure function upper(str,begin,end) result (string)
 character(*), intent(in)    :: str
 integer,optional,intent(in) :: begin,end
 character(len(str))         :: string  ! output string
DESCRIPTION
upper(string) returns a copy of the input string with all characters converted in the optionally specified range to uppercase, assuming ASCII character sets are being used. If no range is specified the entire string is converted to uppercase.
OPTIONS
str string to convert to uppercase begin optional starting position in "str" to begin converting to uppercase end optional ending position in "str" to stop converting to uppercase
RESULTS
upper copy of the input string with all characters converted to uppercase over optionally specified range.
TRIVIA
The terms "uppercase" and "lowercase" date back to the early days of the mechanical printing press. Individual metal alloy casts of each needed letter, or punctuation symbol, were meticulously added to a press block, by hand, before rolling out copies of a page. These metal casts were stored and organized in wooden cases. The more often needed miniscule letters were placed closer to hand, in the lower cases of the work bench. The less often needed, capitalized, majuscule letters, ended up in the harder to reach upper cases.
EXAMPLE
Sample program:
 program demo_upper
 use M_time, only: upper
 implicit none
 character(len=:),allocatable  :: s
    s=' ABCDEFG abcdefg '
    write(*,*) 'mixed-case input string is ....',s
    write(*,*) 'upper-case output string is ...',upper(s)
    write(*,*) 'make first character uppercase  ... ',upper('this is a sentence.',1,1)
    write(*,'(1x,a,*(a:,"+"))') 'upper(3f) is elemental ==>',upper(["abc","def","ghi"])
 end program demo_upper
Expected output
 mixed-case input string is .... ABCDEFG abcdefg
 upper-case output string is ... ABCDEFG ABCDEFG
 make first character uppercase  ... This is a sentence.
 upper(3f) is elemental ==>ABC+DEF+GHI
AUTHOR
John S. Urban
LICENSE
Public Domain
v2mo()
character(len=:) function, allocatable, public m_time::v2mo (integer, intent(in) imonth)
NAME
v2mo(3f) - [M_time] returns the month name of a Common month number (LICENSE:PD)
SYNOPSIS
function v2mo(imonth) result(month_name)
 integer,intent(in)           :: imonth      ! month number (1-12)
 character(len=:),allocatable :: month_name  ! month name
DESCRIPTION
Given a Common Calendar month number, return the name of the month as a string.
OPTIONS
imonth Common month number (1-12). If out of the allowable range the month name returned will be 'UNKNOWN'.
RETURNS
month_name A string representing a month name or the word 'UNKNOWN'
EXAMPLE
Sample program:
 program demo_v2mo
 use M_time, only : v2mo
 implicit none
 integer :: i
    do i=1,13
       write(*,*)v2mo(i)
    enddo
 end program demo_v2mo
results:
 January
 February
 March
 April
 May
 June
 July
 August
 September
 October
 November
 December
 UNKNOWN.
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
value_to_string()
subroutine m_time::value_to_string (class(*), intent(in) gval, character(len=*), intent(out) chars, integer, intent(out), optional length, integer, optional err, character(len=*), intent(in), optional fmt, logical, intent(in), optional trimz) private
NAME
value_to_string(3f) - [M_strings:NUMERIC] return numeric string from a numeric value (LICENSE:PD)
SYNOPSIS
subroutine value_to_string(value,chars[,ilen,ierr,fmt,trimz])
 character(len=*) :: chars  ! minimum of 23 characters required
 !--------
 ! VALUE may be any <em>one</em> of the following types:
 doubleprecision,intent(in)               :: value
 real,intent(in)                          :: value
 integer,intent(in)                       :: value
 logical,intent(in)                       :: value
 !--------
 character(len=*),intent(out)             :: chars
 integer,intent(out),optional             :: ilen
 integer,optional                         :: ierr
 character(len=*),intent(in),optional     :: fmt
 logical,intent(in)                       :: trimz
DESCRIPTION
value_to_string(3f) returns a numeric representation of a numeric value in a string given a numeric value of type REAL, DOUBLEPRECISION, INTEGER or LOGICAL. It creates the string using internal writes. It then removes trailing zeros from non-zero values, and left-justifies the string.
OPTIONS
VALUE input value to be converted to a string FMT You may specify a specific format that produces a string up to the length of CHARS; optional. TRIMZ If a format is supplied the default is not to try to trim trailing zeros. Set TRIMZ to .true. to trim zeros from a string assumed to represent a simple numeric value.
RETURNS
CHARS returned string representing input value, must be at least 23 characters long; or what is required by optional FMT if longer. ILEN position of last non-blank character in returned string; optional. IERR If not zero, error occurred; optional.
EXAMPLE
Sample program:
  program demo_value_to_string
  use M_strings, only: value_to_string
  implicit none
  character(len=80) :: string
  integer           :: ilen
     call value_to_string(3.0/4.0,string,ilen)
     write(*,*) 'The value is [',string(:ilen),']'
     call value_to_string(3.0/4.0,string,ilen,fmt='')
     write(*,*) 'The value is [',string(:ilen),']'
     call value_to_string(3.0/4.0,string,ilen,fmt='("THE VALUE IS ",g0)')
     write(*,*) 'The value is [',string(:ilen),']'
     call value_to_string(1234,string,ilen)
     write(*,*) 'The value is [',string(:ilen),']'
     call value_to_string(1.0d0/3.0d0,string,ilen)
     write(*,*) 'The value is [',string(:ilen),']'
  end program demo_value_to_string
Expected output
 The value is [0.75]
 The value is [      0.7500000000]
 The value is [THE VALUE IS .750000000]
 The value is [1234]
 The value is [0.33333333333333331]
AUTHOR
John S. Urban
LICENSE
Public Domain
References stderr(), and trimzeros().
w2d()
subroutine, public m_time::w2d (integer, intent(in) iso_year, integer, intent(in) iso_week, integer, intent(in) iso_weekday, integer, dimension(8), intent(out) dat)
NAME
w2d(3f) - [M_time] calculate DAT date-time array from iso-8601 Week-numbering year date yyyy-Www-d (LICENSE:PD)
SYNOPSIS
subroutine w2d(iso_year,iso_week,iso_weekday,dat)
 integer,intent(in)      :: iso_year, iso_week, iso_weekday
 integer,intent(out)     :: dat(8)     ! output date array
DESCRIPTION
Given an ISO-8601 week return a "DAT" array defining a date and time, The ISO-8601 is supplied as three integer values defining the ISO year, week of year and weekday.
OPTIONS
iso_year ISO-8601 year number for the given date iso_week ISO-8601 week number for the given date iso_weekday ISO-8601 weekday number for the given date iso_name ISO-8601 Week string for the data in the form "yyyy-Www-d".
RETURNS
dat "DAT" array (an integer array of the same format as the array returned by the intrinsic DATE_AND_TIME(3f)) describing the date to be used, which is the basic time description used by the other M_time(3fm) module procedures.
EXAMPLE
Sample program:
 program demo_w2d
 use M_time, only : w2d, fmtdate
 implicit none
    write(*,'(a)')'Given Monday 29 December 2008 is written "2009-W01-1"'
    call printit(2009,1,1)
    write(*,'(a)')'Given Sunday 3 January 2010 is written "2009-W53-7"'
    call printit(2009,53,7)
    write(*,'(a)')'Given the Gregorian date Sun 31 December 2006 is written 2006-W52-7'
    call printit(2006,52,7)
    write(*,'(a)')'Given 27 September 2008 is 2008-W39-6'
    call printit(2008,39,6)
 contains
 subroutine printit(iso_year,iso_week,iso_weekday)
 integer  :: iso_year, iso_week, iso_weekday ! ISO-8601 Week:   2016-W29-1
 integer  :: dat(8)                          ! input date array
    call w2d(iso_year,iso_week,iso_weekday,dat)
    write(*,'(a,i0)')'GIVEN:           '
    write(*,'(a,i0)')'ISO-8601 year    ',iso_year
    write(*,'(a,i0)')'ISO-8601 week    ',iso_week
    write(*,'(a,i0)')'ISO-8601 weekday ',iso_weekday
    write(*,'(a,i0)')'RESULT:          '
    write(*,'(a,*(i0:,","))')'   DAT array        ',dat
    write(*,'(a,/,77("="))')'    '//fmtdate(dat,'long')
 end subroutine printit
 end program demo_w2d
Results:
 Given Monday 29 December 2008 is written "2009-W01-1"
 GIVEN:
 ISO-8601 year    2009
 ISO-8601 week    1
 ISO-8601 weekday 1
 RESULT:
    DAT array        2008,12,29,-240,0,0,0,0
     Monday, December 29th, 2008 12:00:00 AM UTC-04:00
 =============================================================================
 Given Sunday 3 January 2010 is written "2009-W53-7"
 GIVEN:
 ISO-8601 year    2009
 ISO-8601 week    53
 ISO-8601 weekday 7
 RESULT:
    DAT array        2010,1,3,-240,0,0,0,0
     Sunday, January 3rd, 2010 12:00:00 AM UTC-04:00
 =============================================================================
 Given the Gregorian date Sun 31 December 2006 is written 2006-W52-7
 GIVEN:
 ISO-8601 year    2006
 ISO-8601 week    52
 ISO-8601 weekday 7
 RESULT:
    DAT array        2006,12,31,-240,0,0,0,0
     Sunday, December 31st, 2006 12:00:00 AM UTC-04:00
 =============================================================================
 Given 27 September 2008 is 2008-W39-6
 GIVEN:
 ISO-8601 year    2008
 ISO-8601 week    39
 ISO-8601 weekday 6
 RESULT:
    DAT array        2008,9,27,-240,0,0,0,0
     Saturday, September 27th, 2008 12:00:00 AM UTC-04:00
 =============================================================================
DEFINITION
The ISO-8601 date and time standard was issued by the International Organization for Standardization (ISO). It is used (mainly) in government and business for fiscal years, as well as in timekeeping. The system specifies a week year atop the Gregorian calendar by defining a notation for ordinal weeks of the year.
An ISO week-numbering year (also called ISO year informally) has 52 or 53 full weeks. That is 364 or 371 days instead of the usual 365 or 366 days. The extra week is referred to here as a leap week, although ISO-8601 does not use this term. Weeks start with Monday. The first week of a year is the week that contains the first Thursday of the year (and, hence, always contains 4 January). ISO week year numbering therefore slightly deviates from the Gregorian for some days close to January 1st.
METHOD
Calculating a date given the year, week number and weekday
This method requires that one know the weekday of 4 January of the year in question. Add 3 to the number of this weekday, giving a correction to be used for dates within this year.
Method: Multiply the week number by 7, then add the weekday. From this sum subtract the correction for the year. The result is the ordinal date, which can be converted into a calendar date. If the ordinal date thus obtained is zero or negative, the date belongs to the previous calendar year; if greater than the number of days in the year, to the following year.
Example: year 2008, week 39, Saturday (day 6) Correction for 2008: 5 + 3 = 8 (39 x 7) + 6 = 279 279 - 8 = 271 Ordinal day 271 of a leap year is day 271 - 244 = 27 September Result: 27 September 2008
ISO_NAME
Week date representations are in the format YYYYWww-D.
o [YYYY] indicates the ISO week-numbering year which is slightly different from the traditional Gregorian calendar year. o [Www] is the week number prefixed by the letter W, from W01 through W53. o [D] is the weekday number, from 1 through 7, beginning with Monday and ending with Sunday.
For example, the Gregorian date 31 December 2006 corresponds to the Sunday of the 52nd week of 2006, and is written
2006-W52-7 (extended form) or 2006W527 (compact form).
REFERENCE
From Wikipedia, the free encyclopedia 2016-08-08
AUTHOR
John S. Urban, 2015
LICENSE
Public Domain
References dow(), and o2d().
weekday_oop()
integer function, private m_time::weekday_oop (class(date_time), intent(in) self) private
References dow(), and dt2d().
Variable Documentation
dt_day
real(kind=realtime), parameter, public m_time::dt_day =86400.0d0
dt_hour
real(kind=realtime), parameter, public m_time::dt_hour =3600.0d0
dt_minute
real(kind=realtime), parameter, public m_time::dt_minute =60.0d0
dt_week
real(kind=realtime), parameter, public m_time::dt_week =dt_day*7.0d0
realtime
integer, parameter, public m_time::realtime =kind(0.0d0)
secday
real(kind=realtime), parameter, private m_time::secday =86400.0d0 private