M_time: m_time__oop::date_time Interface Reference
m_time__oop::date_time Interface Reference
Private Member Functions
procedure datout => dt2d_
procedure epoch => epoch_
procedure julian => julian_
procedure mjd => mjd_
procedure ordinal
procedure weekday
procedure format
procedure delta
procedure init => init_dt
procedure, private plus_seconds
generic operator => plus_seconds
procedure, private eq
generic operator => eq
procedure, private lt
generic operator => lt
procedure, private gt
generic operator => gt
procedure, private ge
generic operator => ge
procedure, private le
generic operator => le
procedure, private ne
generic operator => ne
procedure, private minus_seconds
procedure, private minus_date_time
generic operator => minus_seconds
generic operator => minus_date_time
type(date_time) function construct_from_dat (dat)
Private Attributes
integer year =1970
integer month =1
integer day =1
integer tz =0
integer hour =0
integer minute =0
integer second =0
integer millisecond =0
Member Function/Subroutine Documentation
construct_from_dat()
type(date_time) function m_time__oop::date_time::construct_from_dat (integer, dimension(:), intent(in) dat) private
datout()
procedure m_time__oop::date_time::datout private
delta()
procedure m_time__oop::date_time::delta private
epoch()
procedure m_time__oop::date_time::epoch private
eq()
procedure, private m_time__oop::date_time::eq private
format()
procedure m_time__oop::date_time::format private
ge()
procedure, private m_time__oop::date_time::ge private
gt()
procedure, private m_time__oop::date_time::gt private
init()
procedure m_time__oop::date_time::init private
julian()
procedure m_time__oop::date_time::julian private
le()
procedure, private m_time__oop::date_time::le private
lt()
procedure, private m_time__oop::date_time::lt private
minus_date_time()
procedure, private m_time__oop::date_time::minus_date_time private
minus_seconds()
procedure, private m_time__oop::date_time::minus_seconds private
mjd()
procedure m_time__oop::date_time::mjd private
ne()
procedure, private m_time__oop::date_time::ne private
operator() [1/9]
generic m_time__oop::date_time::operator private
References m_time__oop::eq().
operator() [2/9]
generic m_time__oop::date_time::operator private
References m_time__oop::ge().
operator() [3/9]
generic m_time__oop::date_time::operator private
References m_time__oop::gt().
operator() [4/9]
generic m_time__oop::date_time::operator private
References m_time__oop::le().
operator() [5/9]
generic m_time__oop::date_time::operator private
References m_time__oop::lt().
operator() [6/9]
generic m_time__oop::date_time::operator private
References m_time__oop::construct_from_dat(), and m_time__oop::minus_date_time().
operator() [7/9]
generic m_time__oop::date_time::operator private
References m_time__oop::minus_seconds().
operator() [8/9]
generic m_time__oop::date_time::operator private
References m_time__oop::ne().
operator() [9/9]
generic m_time__oop::date_time::operator private
References m_time__oop::plus_seconds().
ordinal()
procedure m_time__oop::date_time::ordinal private
plus_seconds()
procedure, private m_time__oop::date_time::plus_seconds private
weekday()
procedure m_time__oop::date_time::weekday private
Member Data Documentation
day
integer m_time__oop::date_time::day =1 private
hour
integer m_time__oop::date_time::hour =0 private
millisecond
integer m_time__oop::date_time::millisecond =0 private
minute
integer m_time__oop::date_time::minute =0 private
month
integer m_time__oop::date_time::month =1 private
second
integer m_time__oop::date_time::second =0 private
tz
integer m_time__oop::date_time::tz =0 private
year
integer m_time__oop::date_time::year =1970 private
The documentation for this interface was generated from the following file:
/home/urbanjs/venus/V600/github/M_time/src/M_time__oop.f90