#!/bin/bash
cd $(dirname $0)/..
export UFPP_DOCUMENT_DIR=$(pwd)/../src/source
for NAME in MONTH/month.ff SEC2DAYS/sec2days.ff TODAY/today.ff DAYS2SEC/days2sec.FF NOW/now.ff
do
   ufpp TESTPRG90 \
   --cstyle doxygen \
   --verbose \
   --allow_links \
   -system .true. \
   -i $NAME \
   -o $(dirname $NAME)/$(basename $(basename $NAME .FF) .ff ).f90
done
exit
